// Code generated by counterfeiter. DO NOT EDIT.
package sbomfakes

import (
	"sync"

	"github.com/interlynk-io/sbomqs/pkg/sbom"
)

type FakeGetSignature struct {
	GetBlobStub        func() string
	getBlobMutex       sync.RWMutex
	getBlobArgsForCall []struct {
	}
	getBlobReturns struct {
		result1 string
	}
	getBlobReturnsOnCall map[int]struct {
		result1 string
	}
	GetPublicKeyStub        func() string
	getPublicKeyMutex       sync.RWMutex
	getPublicKeyArgsForCall []struct {
	}
	getPublicKeyReturns struct {
		result1 string
	}
	getPublicKeyReturnsOnCall map[int]struct {
		result1 string
	}
	GetSigValueStub        func() string
	getSigValueMutex       sync.RWMutex
	getSigValueArgsForCall []struct {
	}
	getSigValueReturns struct {
		result1 string
	}
	getSigValueReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGetSignature) GetBlob() string {
	fake.getBlobMutex.Lock()
	ret, specificReturn := fake.getBlobReturnsOnCall[len(fake.getBlobArgsForCall)]
	fake.getBlobArgsForCall = append(fake.getBlobArgsForCall, struct {
	}{})
	stub := fake.GetBlobStub
	fakeReturns := fake.getBlobReturns
	fake.recordInvocation("GetBlob", []interface{}{})
	fake.getBlobMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetSignature) GetBlobCallCount() int {
	fake.getBlobMutex.RLock()
	defer fake.getBlobMutex.RUnlock()
	return len(fake.getBlobArgsForCall)
}

func (fake *FakeGetSignature) GetBlobCalls(stub func() string) {
	fake.getBlobMutex.Lock()
	defer fake.getBlobMutex.Unlock()
	fake.GetBlobStub = stub
}

func (fake *FakeGetSignature) GetBlobReturns(result1 string) {
	fake.getBlobMutex.Lock()
	defer fake.getBlobMutex.Unlock()
	fake.GetBlobStub = nil
	fake.getBlobReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetSignature) GetBlobReturnsOnCall(i int, result1 string) {
	fake.getBlobMutex.Lock()
	defer fake.getBlobMutex.Unlock()
	fake.GetBlobStub = nil
	if fake.getBlobReturnsOnCall == nil {
		fake.getBlobReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getBlobReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetSignature) GetPublicKey() string {
	fake.getPublicKeyMutex.Lock()
	ret, specificReturn := fake.getPublicKeyReturnsOnCall[len(fake.getPublicKeyArgsForCall)]
	fake.getPublicKeyArgsForCall = append(fake.getPublicKeyArgsForCall, struct {
	}{})
	stub := fake.GetPublicKeyStub
	fakeReturns := fake.getPublicKeyReturns
	fake.recordInvocation("GetPublicKey", []interface{}{})
	fake.getPublicKeyMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetSignature) GetPublicKeyCallCount() int {
	fake.getPublicKeyMutex.RLock()
	defer fake.getPublicKeyMutex.RUnlock()
	return len(fake.getPublicKeyArgsForCall)
}

func (fake *FakeGetSignature) GetPublicKeyCalls(stub func() string) {
	fake.getPublicKeyMutex.Lock()
	defer fake.getPublicKeyMutex.Unlock()
	fake.GetPublicKeyStub = stub
}

func (fake *FakeGetSignature) GetPublicKeyReturns(result1 string) {
	fake.getPublicKeyMutex.Lock()
	defer fake.getPublicKeyMutex.Unlock()
	fake.GetPublicKeyStub = nil
	fake.getPublicKeyReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetSignature) GetPublicKeyReturnsOnCall(i int, result1 string) {
	fake.getPublicKeyMutex.Lock()
	defer fake.getPublicKeyMutex.Unlock()
	fake.GetPublicKeyStub = nil
	if fake.getPublicKeyReturnsOnCall == nil {
		fake.getPublicKeyReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getPublicKeyReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetSignature) GetSigValue() string {
	fake.getSigValueMutex.Lock()
	ret, specificReturn := fake.getSigValueReturnsOnCall[len(fake.getSigValueArgsForCall)]
	fake.getSigValueArgsForCall = append(fake.getSigValueArgsForCall, struct {
	}{})
	stub := fake.GetSigValueStub
	fakeReturns := fake.getSigValueReturns
	fake.recordInvocation("GetSigValue", []interface{}{})
	fake.getSigValueMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetSignature) GetSigValueCallCount() int {
	fake.getSigValueMutex.RLock()
	defer fake.getSigValueMutex.RUnlock()
	return len(fake.getSigValueArgsForCall)
}

func (fake *FakeGetSignature) GetSigValueCalls(stub func() string) {
	fake.getSigValueMutex.Lock()
	defer fake.getSigValueMutex.Unlock()
	fake.GetSigValueStub = stub
}

func (fake *FakeGetSignature) GetSigValueReturns(result1 string) {
	fake.getSigValueMutex.Lock()
	defer fake.getSigValueMutex.Unlock()
	fake.GetSigValueStub = nil
	fake.getSigValueReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetSignature) GetSigValueReturnsOnCall(i int, result1 string) {
	fake.getSigValueMutex.Lock()
	defer fake.getSigValueMutex.Unlock()
	fake.GetSigValueStub = nil
	if fake.getSigValueReturnsOnCall == nil {
		fake.getSigValueReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getSigValueReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetSignature) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGetSignature) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sbom.GetSignature = new(FakeGetSignature)
