// Code generated by counterfeiter. DO NOT EDIT.
package sbomfakes

import (
	"sync"

	"github.com/interlynk-io/sbomqs/v2/pkg/sbom"
)

type FakeGetPrimaryComp struct {
	GetDependenciesStub        func() []string
	getDependenciesMutex       sync.RWMutex
	getDependenciesArgsForCall []struct {
	}
	getDependenciesReturns struct {
		result1 []string
	}
	getDependenciesReturnsOnCall map[int]struct {
		result1 []string
	}
	GetIDStub        func() string
	getIDMutex       sync.RWMutex
	getIDArgsForCall []struct {
	}
	getIDReturns struct {
		result1 string
	}
	getIDReturnsOnCall map[int]struct {
		result1 string
	}
	GetNameStub        func() string
	getNameMutex       sync.RWMutex
	getNameArgsForCall []struct {
	}
	getNameReturns struct {
		result1 string
	}
	getNameReturnsOnCall map[int]struct {
		result1 string
	}
	GetTotalNoOfDependenciesStub        func() int
	getTotalNoOfDependenciesMutex       sync.RWMutex
	getTotalNoOfDependenciesArgsForCall []struct {
	}
	getTotalNoOfDependenciesReturns struct {
		result1 int
	}
	getTotalNoOfDependenciesReturnsOnCall map[int]struct {
		result1 int
	}
	GetVersionStub        func() string
	getVersionMutex       sync.RWMutex
	getVersionArgsForCall []struct {
	}
	getVersionReturns struct {
		result1 string
	}
	getVersionReturnsOnCall map[int]struct {
		result1 string
	}
	HasDependenciesStub        func() bool
	hasDependenciesMutex       sync.RWMutex
	hasDependenciesArgsForCall []struct {
	}
	hasDependenciesReturns struct {
		result1 bool
	}
	hasDependenciesReturnsOnCall map[int]struct {
		result1 bool
	}
	IsPresentStub        func() bool
	isPresentMutex       sync.RWMutex
	isPresentArgsForCall []struct {
	}
	isPresentReturns struct {
		result1 bool
	}
	isPresentReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGetPrimaryComp) GetDependencies() []string {
	fake.getDependenciesMutex.Lock()
	ret, specificReturn := fake.getDependenciesReturnsOnCall[len(fake.getDependenciesArgsForCall)]
	fake.getDependenciesArgsForCall = append(fake.getDependenciesArgsForCall, struct {
	}{})
	stub := fake.GetDependenciesStub
	fakeReturns := fake.getDependenciesReturns
	fake.recordInvocation("GetDependencies", []interface{}{})
	fake.getDependenciesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetPrimaryComp) GetDependenciesCallCount() int {
	fake.getDependenciesMutex.RLock()
	defer fake.getDependenciesMutex.RUnlock()
	return len(fake.getDependenciesArgsForCall)
}

func (fake *FakeGetPrimaryComp) GetDependenciesCalls(stub func() []string) {
	fake.getDependenciesMutex.Lock()
	defer fake.getDependenciesMutex.Unlock()
	fake.GetDependenciesStub = stub
}

func (fake *FakeGetPrimaryComp) GetDependenciesReturns(result1 []string) {
	fake.getDependenciesMutex.Lock()
	defer fake.getDependenciesMutex.Unlock()
	fake.GetDependenciesStub = nil
	fake.getDependenciesReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeGetPrimaryComp) GetDependenciesReturnsOnCall(i int, result1 []string) {
	fake.getDependenciesMutex.Lock()
	defer fake.getDependenciesMutex.Unlock()
	fake.GetDependenciesStub = nil
	if fake.getDependenciesReturnsOnCall == nil {
		fake.getDependenciesReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.getDependenciesReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeGetPrimaryComp) GetID() string {
	fake.getIDMutex.Lock()
	ret, specificReturn := fake.getIDReturnsOnCall[len(fake.getIDArgsForCall)]
	fake.getIDArgsForCall = append(fake.getIDArgsForCall, struct {
	}{})
	stub := fake.GetIDStub
	fakeReturns := fake.getIDReturns
	fake.recordInvocation("GetID", []interface{}{})
	fake.getIDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetPrimaryComp) GetIDCallCount() int {
	fake.getIDMutex.RLock()
	defer fake.getIDMutex.RUnlock()
	return len(fake.getIDArgsForCall)
}

func (fake *FakeGetPrimaryComp) GetIDCalls(stub func() string) {
	fake.getIDMutex.Lock()
	defer fake.getIDMutex.Unlock()
	fake.GetIDStub = stub
}

func (fake *FakeGetPrimaryComp) GetIDReturns(result1 string) {
	fake.getIDMutex.Lock()
	defer fake.getIDMutex.Unlock()
	fake.GetIDStub = nil
	fake.getIDReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetPrimaryComp) GetIDReturnsOnCall(i int, result1 string) {
	fake.getIDMutex.Lock()
	defer fake.getIDMutex.Unlock()
	fake.GetIDStub = nil
	if fake.getIDReturnsOnCall == nil {
		fake.getIDReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getIDReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetPrimaryComp) GetName() string {
	fake.getNameMutex.Lock()
	ret, specificReturn := fake.getNameReturnsOnCall[len(fake.getNameArgsForCall)]
	fake.getNameArgsForCall = append(fake.getNameArgsForCall, struct {
	}{})
	stub := fake.GetNameStub
	fakeReturns := fake.getNameReturns
	fake.recordInvocation("GetName", []interface{}{})
	fake.getNameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetPrimaryComp) GetNameCallCount() int {
	fake.getNameMutex.RLock()
	defer fake.getNameMutex.RUnlock()
	return len(fake.getNameArgsForCall)
}

func (fake *FakeGetPrimaryComp) GetNameCalls(stub func() string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = stub
}

func (fake *FakeGetPrimaryComp) GetNameReturns(result1 string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = nil
	fake.getNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetPrimaryComp) GetNameReturnsOnCall(i int, result1 string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = nil
	if fake.getNameReturnsOnCall == nil {
		fake.getNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetPrimaryComp) GetTotalNoOfDependencies() int {
	fake.getTotalNoOfDependenciesMutex.Lock()
	ret, specificReturn := fake.getTotalNoOfDependenciesReturnsOnCall[len(fake.getTotalNoOfDependenciesArgsForCall)]
	fake.getTotalNoOfDependenciesArgsForCall = append(fake.getTotalNoOfDependenciesArgsForCall, struct {
	}{})
	stub := fake.GetTotalNoOfDependenciesStub
	fakeReturns := fake.getTotalNoOfDependenciesReturns
	fake.recordInvocation("GetTotalNoOfDependencies", []interface{}{})
	fake.getTotalNoOfDependenciesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetPrimaryComp) GetTotalNoOfDependenciesCallCount() int {
	fake.getTotalNoOfDependenciesMutex.RLock()
	defer fake.getTotalNoOfDependenciesMutex.RUnlock()
	return len(fake.getTotalNoOfDependenciesArgsForCall)
}

func (fake *FakeGetPrimaryComp) GetTotalNoOfDependenciesCalls(stub func() int) {
	fake.getTotalNoOfDependenciesMutex.Lock()
	defer fake.getTotalNoOfDependenciesMutex.Unlock()
	fake.GetTotalNoOfDependenciesStub = stub
}

func (fake *FakeGetPrimaryComp) GetTotalNoOfDependenciesReturns(result1 int) {
	fake.getTotalNoOfDependenciesMutex.Lock()
	defer fake.getTotalNoOfDependenciesMutex.Unlock()
	fake.GetTotalNoOfDependenciesStub = nil
	fake.getTotalNoOfDependenciesReturns = struct {
		result1 int
	}{result1}
}

func (fake *FakeGetPrimaryComp) GetTotalNoOfDependenciesReturnsOnCall(i int, result1 int) {
	fake.getTotalNoOfDependenciesMutex.Lock()
	defer fake.getTotalNoOfDependenciesMutex.Unlock()
	fake.GetTotalNoOfDependenciesStub = nil
	if fake.getTotalNoOfDependenciesReturnsOnCall == nil {
		fake.getTotalNoOfDependenciesReturnsOnCall = make(map[int]struct {
			result1 int
		})
	}
	fake.getTotalNoOfDependenciesReturnsOnCall[i] = struct {
		result1 int
	}{result1}
}

func (fake *FakeGetPrimaryComp) GetVersion() string {
	fake.getVersionMutex.Lock()
	ret, specificReturn := fake.getVersionReturnsOnCall[len(fake.getVersionArgsForCall)]
	fake.getVersionArgsForCall = append(fake.getVersionArgsForCall, struct {
	}{})
	stub := fake.GetVersionStub
	fakeReturns := fake.getVersionReturns
	fake.recordInvocation("GetVersion", []interface{}{})
	fake.getVersionMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetPrimaryComp) GetVersionCallCount() int {
	fake.getVersionMutex.RLock()
	defer fake.getVersionMutex.RUnlock()
	return len(fake.getVersionArgsForCall)
}

func (fake *FakeGetPrimaryComp) GetVersionCalls(stub func() string) {
	fake.getVersionMutex.Lock()
	defer fake.getVersionMutex.Unlock()
	fake.GetVersionStub = stub
}

func (fake *FakeGetPrimaryComp) GetVersionReturns(result1 string) {
	fake.getVersionMutex.Lock()
	defer fake.getVersionMutex.Unlock()
	fake.GetVersionStub = nil
	fake.getVersionReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetPrimaryComp) GetVersionReturnsOnCall(i int, result1 string) {
	fake.getVersionMutex.Lock()
	defer fake.getVersionMutex.Unlock()
	fake.GetVersionStub = nil
	if fake.getVersionReturnsOnCall == nil {
		fake.getVersionReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getVersionReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetPrimaryComp) HasDependencies() bool {
	fake.hasDependenciesMutex.Lock()
	ret, specificReturn := fake.hasDependenciesReturnsOnCall[len(fake.hasDependenciesArgsForCall)]
	fake.hasDependenciesArgsForCall = append(fake.hasDependenciesArgsForCall, struct {
	}{})
	stub := fake.HasDependenciesStub
	fakeReturns := fake.hasDependenciesReturns
	fake.recordInvocation("HasDependencies", []interface{}{})
	fake.hasDependenciesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetPrimaryComp) HasDependenciesCallCount() int {
	fake.hasDependenciesMutex.RLock()
	defer fake.hasDependenciesMutex.RUnlock()
	return len(fake.hasDependenciesArgsForCall)
}

func (fake *FakeGetPrimaryComp) HasDependenciesCalls(stub func() bool) {
	fake.hasDependenciesMutex.Lock()
	defer fake.hasDependenciesMutex.Unlock()
	fake.HasDependenciesStub = stub
}

func (fake *FakeGetPrimaryComp) HasDependenciesReturns(result1 bool) {
	fake.hasDependenciesMutex.Lock()
	defer fake.hasDependenciesMutex.Unlock()
	fake.HasDependenciesStub = nil
	fake.hasDependenciesReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGetPrimaryComp) HasDependenciesReturnsOnCall(i int, result1 bool) {
	fake.hasDependenciesMutex.Lock()
	defer fake.hasDependenciesMutex.Unlock()
	fake.HasDependenciesStub = nil
	if fake.hasDependenciesReturnsOnCall == nil {
		fake.hasDependenciesReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.hasDependenciesReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGetPrimaryComp) IsPresent() bool {
	fake.isPresentMutex.Lock()
	ret, specificReturn := fake.isPresentReturnsOnCall[len(fake.isPresentArgsForCall)]
	fake.isPresentArgsForCall = append(fake.isPresentArgsForCall, struct {
	}{})
	stub := fake.IsPresentStub
	fakeReturns := fake.isPresentReturns
	fake.recordInvocation("IsPresent", []interface{}{})
	fake.isPresentMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetPrimaryComp) IsPresentCallCount() int {
	fake.isPresentMutex.RLock()
	defer fake.isPresentMutex.RUnlock()
	return len(fake.isPresentArgsForCall)
}

func (fake *FakeGetPrimaryComp) IsPresentCalls(stub func() bool) {
	fake.isPresentMutex.Lock()
	defer fake.isPresentMutex.Unlock()
	fake.IsPresentStub = stub
}

func (fake *FakeGetPrimaryComp) IsPresentReturns(result1 bool) {
	fake.isPresentMutex.Lock()
	defer fake.isPresentMutex.Unlock()
	fake.IsPresentStub = nil
	fake.isPresentReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGetPrimaryComp) IsPresentReturnsOnCall(i int, result1 bool) {
	fake.isPresentMutex.Lock()
	defer fake.isPresentMutex.Unlock()
	fake.IsPresentStub = nil
	if fake.isPresentReturnsOnCall == nil {
		fake.isPresentReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isPresentReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGetPrimaryComp) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGetPrimaryComp) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sbom.GetPrimaryComp = new(FakeGetPrimaryComp)
