// Code generated by counterfeiter. DO NOT EDIT.
package sbomfakes

import (
	"sync"

	"github.com/interlynk-io/sbomqs/pkg/licenses"
	"github.com/interlynk-io/sbomqs/pkg/sbom"
)

type FakeSpec struct {
	FileFormatStub        func() string
	fileFormatMutex       sync.RWMutex
	fileFormatArgsForCall []struct {
	}
	fileFormatReturns struct {
		result1 string
	}
	fileFormatReturnsOnCall map[int]struct {
		result1 string
	}
	GetCommentStub        func() string
	getCommentMutex       sync.RWMutex
	getCommentArgsForCall []struct {
	}
	getCommentReturns struct {
		result1 string
	}
	getCommentReturnsOnCall map[int]struct {
		result1 string
	}
	GetCreationTimestampStub        func() string
	getCreationTimestampMutex       sync.RWMutex
	getCreationTimestampArgsForCall []struct {
	}
	getCreationTimestampReturns struct {
		result1 string
	}
	getCreationTimestampReturnsOnCall map[int]struct {
		result1 string
	}
	GetExtDocRefStub        func() []string
	getExtDocRefMutex       sync.RWMutex
	getExtDocRefArgsForCall []struct {
	}
	getExtDocRefReturns struct {
		result1 []string
	}
	getExtDocRefReturnsOnCall map[int]struct {
		result1 []string
	}
	GetLicensesStub        func() []licenses.License
	getLicensesMutex       sync.RWMutex
	getLicensesArgsForCall []struct {
	}
	getLicensesReturns struct {
		result1 []licenses.License
	}
	getLicensesReturnsOnCall map[int]struct {
		result1 []licenses.License
	}
	GetNameStub        func() string
	getNameMutex       sync.RWMutex
	getNameArgsForCall []struct {
	}
	getNameReturns struct {
		result1 string
	}
	getNameReturnsOnCall map[int]struct {
		result1 string
	}
	GetNamespaceStub        func() string
	getNamespaceMutex       sync.RWMutex
	getNamespaceArgsForCall []struct {
	}
	getNamespaceReturns struct {
		result1 string
	}
	getNamespaceReturnsOnCall map[int]struct {
		result1 string
	}
	GetOrganizationStub        func() string
	getOrganizationMutex       sync.RWMutex
	getOrganizationArgsForCall []struct {
	}
	getOrganizationReturns struct {
		result1 string
	}
	getOrganizationReturnsOnCall map[int]struct {
		result1 string
	}
	GetSpdxIDStub        func() string
	getSpdxIDMutex       sync.RWMutex
	getSpdxIDArgsForCall []struct {
	}
	getSpdxIDReturns struct {
		result1 string
	}
	getSpdxIDReturnsOnCall map[int]struct {
		result1 string
	}
	GetSpecTypeStub        func() string
	getSpecTypeMutex       sync.RWMutex
	getSpecTypeArgsForCall []struct {
	}
	getSpecTypeReturns struct {
		result1 string
	}
	getSpecTypeReturnsOnCall map[int]struct {
		result1 string
	}
	GetURIStub        func() string
	getURIMutex       sync.RWMutex
	getURIArgsForCall []struct {
	}
	getURIReturns struct {
		result1 string
	}
	getURIReturnsOnCall map[int]struct {
		result1 string
	}
	GetVersionStub        func() string
	getVersionMutex       sync.RWMutex
	getVersionArgsForCall []struct {
	}
	getVersionReturns struct {
		result1 string
	}
	getVersionReturnsOnCall map[int]struct {
		result1 string
	}
	ParsableStub        func() bool
	parsableMutex       sync.RWMutex
	parsableArgsForCall []struct {
	}
	parsableReturns struct {
		result1 bool
	}
	parsableReturnsOnCall map[int]struct {
		result1 bool
	}
	RequiredFieldsStub        func() bool
	requiredFieldsMutex       sync.RWMutex
	requiredFieldsArgsForCall []struct {
	}
	requiredFieldsReturns struct {
		result1 bool
	}
	requiredFieldsReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSpec) FileFormat() string {
	fake.fileFormatMutex.Lock()
	ret, specificReturn := fake.fileFormatReturnsOnCall[len(fake.fileFormatArgsForCall)]
	fake.fileFormatArgsForCall = append(fake.fileFormatArgsForCall, struct {
	}{})
	stub := fake.FileFormatStub
	fakeReturns := fake.fileFormatReturns
	fake.recordInvocation("FileFormat", []interface{}{})
	fake.fileFormatMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpec) FileFormatCallCount() int {
	fake.fileFormatMutex.RLock()
	defer fake.fileFormatMutex.RUnlock()
	return len(fake.fileFormatArgsForCall)
}

func (fake *FakeSpec) FileFormatCalls(stub func() string) {
	fake.fileFormatMutex.Lock()
	defer fake.fileFormatMutex.Unlock()
	fake.FileFormatStub = stub
}

func (fake *FakeSpec) FileFormatReturns(result1 string) {
	fake.fileFormatMutex.Lock()
	defer fake.fileFormatMutex.Unlock()
	fake.FileFormatStub = nil
	fake.fileFormatReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) FileFormatReturnsOnCall(i int, result1 string) {
	fake.fileFormatMutex.Lock()
	defer fake.fileFormatMutex.Unlock()
	fake.FileFormatStub = nil
	if fake.fileFormatReturnsOnCall == nil {
		fake.fileFormatReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.fileFormatReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetComment() string {
	fake.getCommentMutex.Lock()
	ret, specificReturn := fake.getCommentReturnsOnCall[len(fake.getCommentArgsForCall)]
	fake.getCommentArgsForCall = append(fake.getCommentArgsForCall, struct {
	}{})
	stub := fake.GetCommentStub
	fakeReturns := fake.getCommentReturns
	fake.recordInvocation("GetComment", []interface{}{})
	fake.getCommentMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpec) GetCommentCallCount() int {
	fake.getCommentMutex.RLock()
	defer fake.getCommentMutex.RUnlock()
	return len(fake.getCommentArgsForCall)
}

func (fake *FakeSpec) GetCommentCalls(stub func() string) {
	fake.getCommentMutex.Lock()
	defer fake.getCommentMutex.Unlock()
	fake.GetCommentStub = stub
}

func (fake *FakeSpec) GetCommentReturns(result1 string) {
	fake.getCommentMutex.Lock()
	defer fake.getCommentMutex.Unlock()
	fake.GetCommentStub = nil
	fake.getCommentReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetCommentReturnsOnCall(i int, result1 string) {
	fake.getCommentMutex.Lock()
	defer fake.getCommentMutex.Unlock()
	fake.GetCommentStub = nil
	if fake.getCommentReturnsOnCall == nil {
		fake.getCommentReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getCommentReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetCreationTimestamp() string {
	fake.getCreationTimestampMutex.Lock()
	ret, specificReturn := fake.getCreationTimestampReturnsOnCall[len(fake.getCreationTimestampArgsForCall)]
	fake.getCreationTimestampArgsForCall = append(fake.getCreationTimestampArgsForCall, struct {
	}{})
	stub := fake.GetCreationTimestampStub
	fakeReturns := fake.getCreationTimestampReturns
	fake.recordInvocation("GetCreationTimestamp", []interface{}{})
	fake.getCreationTimestampMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpec) GetCreationTimestampCallCount() int {
	fake.getCreationTimestampMutex.RLock()
	defer fake.getCreationTimestampMutex.RUnlock()
	return len(fake.getCreationTimestampArgsForCall)
}

func (fake *FakeSpec) GetCreationTimestampCalls(stub func() string) {
	fake.getCreationTimestampMutex.Lock()
	defer fake.getCreationTimestampMutex.Unlock()
	fake.GetCreationTimestampStub = stub
}

func (fake *FakeSpec) GetCreationTimestampReturns(result1 string) {
	fake.getCreationTimestampMutex.Lock()
	defer fake.getCreationTimestampMutex.Unlock()
	fake.GetCreationTimestampStub = nil
	fake.getCreationTimestampReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetCreationTimestampReturnsOnCall(i int, result1 string) {
	fake.getCreationTimestampMutex.Lock()
	defer fake.getCreationTimestampMutex.Unlock()
	fake.GetCreationTimestampStub = nil
	if fake.getCreationTimestampReturnsOnCall == nil {
		fake.getCreationTimestampReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getCreationTimestampReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetExtDocRef() []string {
	fake.getExtDocRefMutex.Lock()
	ret, specificReturn := fake.getExtDocRefReturnsOnCall[len(fake.getExtDocRefArgsForCall)]
	fake.getExtDocRefArgsForCall = append(fake.getExtDocRefArgsForCall, struct {
	}{})
	stub := fake.GetExtDocRefStub
	fakeReturns := fake.getExtDocRefReturns
	fake.recordInvocation("GetExtDocRef", []interface{}{})
	fake.getExtDocRefMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpec) GetExtDocRefCallCount() int {
	fake.getExtDocRefMutex.RLock()
	defer fake.getExtDocRefMutex.RUnlock()
	return len(fake.getExtDocRefArgsForCall)
}

func (fake *FakeSpec) GetExtDocRefCalls(stub func() []string) {
	fake.getExtDocRefMutex.Lock()
	defer fake.getExtDocRefMutex.Unlock()
	fake.GetExtDocRefStub = stub
}

func (fake *FakeSpec) GetExtDocRefReturns(result1 []string) {
	fake.getExtDocRefMutex.Lock()
	defer fake.getExtDocRefMutex.Unlock()
	fake.GetExtDocRefStub = nil
	fake.getExtDocRefReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeSpec) GetExtDocRefReturnsOnCall(i int, result1 []string) {
	fake.getExtDocRefMutex.Lock()
	defer fake.getExtDocRefMutex.Unlock()
	fake.GetExtDocRefStub = nil
	if fake.getExtDocRefReturnsOnCall == nil {
		fake.getExtDocRefReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.getExtDocRefReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeSpec) GetLicenses() []licenses.License {
	fake.getLicensesMutex.Lock()
	ret, specificReturn := fake.getLicensesReturnsOnCall[len(fake.getLicensesArgsForCall)]
	fake.getLicensesArgsForCall = append(fake.getLicensesArgsForCall, struct {
	}{})
	stub := fake.GetLicensesStub
	fakeReturns := fake.getLicensesReturns
	fake.recordInvocation("GetLicenses", []interface{}{})
	fake.getLicensesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpec) GetLicensesCallCount() int {
	fake.getLicensesMutex.RLock()
	defer fake.getLicensesMutex.RUnlock()
	return len(fake.getLicensesArgsForCall)
}

func (fake *FakeSpec) GetLicensesCalls(stub func() []licenses.License) {
	fake.getLicensesMutex.Lock()
	defer fake.getLicensesMutex.Unlock()
	fake.GetLicensesStub = stub
}

func (fake *FakeSpec) GetLicensesReturns(result1 []licenses.License) {
	fake.getLicensesMutex.Lock()
	defer fake.getLicensesMutex.Unlock()
	fake.GetLicensesStub = nil
	fake.getLicensesReturns = struct {
		result1 []licenses.License
	}{result1}
}

func (fake *FakeSpec) GetLicensesReturnsOnCall(i int, result1 []licenses.License) {
	fake.getLicensesMutex.Lock()
	defer fake.getLicensesMutex.Unlock()
	fake.GetLicensesStub = nil
	if fake.getLicensesReturnsOnCall == nil {
		fake.getLicensesReturnsOnCall = make(map[int]struct {
			result1 []licenses.License
		})
	}
	fake.getLicensesReturnsOnCall[i] = struct {
		result1 []licenses.License
	}{result1}
}

func (fake *FakeSpec) GetName() string {
	fake.getNameMutex.Lock()
	ret, specificReturn := fake.getNameReturnsOnCall[len(fake.getNameArgsForCall)]
	fake.getNameArgsForCall = append(fake.getNameArgsForCall, struct {
	}{})
	stub := fake.GetNameStub
	fakeReturns := fake.getNameReturns
	fake.recordInvocation("GetName", []interface{}{})
	fake.getNameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpec) GetNameCallCount() int {
	fake.getNameMutex.RLock()
	defer fake.getNameMutex.RUnlock()
	return len(fake.getNameArgsForCall)
}

func (fake *FakeSpec) GetNameCalls(stub func() string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = stub
}

func (fake *FakeSpec) GetNameReturns(result1 string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = nil
	fake.getNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetNameReturnsOnCall(i int, result1 string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = nil
	if fake.getNameReturnsOnCall == nil {
		fake.getNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetNamespace() string {
	fake.getNamespaceMutex.Lock()
	ret, specificReturn := fake.getNamespaceReturnsOnCall[len(fake.getNamespaceArgsForCall)]
	fake.getNamespaceArgsForCall = append(fake.getNamespaceArgsForCall, struct {
	}{})
	stub := fake.GetNamespaceStub
	fakeReturns := fake.getNamespaceReturns
	fake.recordInvocation("GetNamespace", []interface{}{})
	fake.getNamespaceMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpec) GetNamespaceCallCount() int {
	fake.getNamespaceMutex.RLock()
	defer fake.getNamespaceMutex.RUnlock()
	return len(fake.getNamespaceArgsForCall)
}

func (fake *FakeSpec) GetNamespaceCalls(stub func() string) {
	fake.getNamespaceMutex.Lock()
	defer fake.getNamespaceMutex.Unlock()
	fake.GetNamespaceStub = stub
}

func (fake *FakeSpec) GetNamespaceReturns(result1 string) {
	fake.getNamespaceMutex.Lock()
	defer fake.getNamespaceMutex.Unlock()
	fake.GetNamespaceStub = nil
	fake.getNamespaceReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetNamespaceReturnsOnCall(i int, result1 string) {
	fake.getNamespaceMutex.Lock()
	defer fake.getNamespaceMutex.Unlock()
	fake.GetNamespaceStub = nil
	if fake.getNamespaceReturnsOnCall == nil {
		fake.getNamespaceReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getNamespaceReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetOrganization() string {
	fake.getOrganizationMutex.Lock()
	ret, specificReturn := fake.getOrganizationReturnsOnCall[len(fake.getOrganizationArgsForCall)]
	fake.getOrganizationArgsForCall = append(fake.getOrganizationArgsForCall, struct {
	}{})
	stub := fake.GetOrganizationStub
	fakeReturns := fake.getOrganizationReturns
	fake.recordInvocation("GetOrganization", []interface{}{})
	fake.getOrganizationMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpec) GetOrganizationCallCount() int {
	fake.getOrganizationMutex.RLock()
	defer fake.getOrganizationMutex.RUnlock()
	return len(fake.getOrganizationArgsForCall)
}

func (fake *FakeSpec) GetOrganizationCalls(stub func() string) {
	fake.getOrganizationMutex.Lock()
	defer fake.getOrganizationMutex.Unlock()
	fake.GetOrganizationStub = stub
}

func (fake *FakeSpec) GetOrganizationReturns(result1 string) {
	fake.getOrganizationMutex.Lock()
	defer fake.getOrganizationMutex.Unlock()
	fake.GetOrganizationStub = nil
	fake.getOrganizationReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetOrganizationReturnsOnCall(i int, result1 string) {
	fake.getOrganizationMutex.Lock()
	defer fake.getOrganizationMutex.Unlock()
	fake.GetOrganizationStub = nil
	if fake.getOrganizationReturnsOnCall == nil {
		fake.getOrganizationReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getOrganizationReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetSpdxID() string {
	fake.getSpdxIDMutex.Lock()
	ret, specificReturn := fake.getSpdxIDReturnsOnCall[len(fake.getSpdxIDArgsForCall)]
	fake.getSpdxIDArgsForCall = append(fake.getSpdxIDArgsForCall, struct {
	}{})
	stub := fake.GetSpdxIDStub
	fakeReturns := fake.getSpdxIDReturns
	fake.recordInvocation("GetSpdxID", []interface{}{})
	fake.getSpdxIDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpec) GetSpdxIDCallCount() int {
	fake.getSpdxIDMutex.RLock()
	defer fake.getSpdxIDMutex.RUnlock()
	return len(fake.getSpdxIDArgsForCall)
}

func (fake *FakeSpec) GetSpdxIDCalls(stub func() string) {
	fake.getSpdxIDMutex.Lock()
	defer fake.getSpdxIDMutex.Unlock()
	fake.GetSpdxIDStub = stub
}

func (fake *FakeSpec) GetSpdxIDReturns(result1 string) {
	fake.getSpdxIDMutex.Lock()
	defer fake.getSpdxIDMutex.Unlock()
	fake.GetSpdxIDStub = nil
	fake.getSpdxIDReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetSpdxIDReturnsOnCall(i int, result1 string) {
	fake.getSpdxIDMutex.Lock()
	defer fake.getSpdxIDMutex.Unlock()
	fake.GetSpdxIDStub = nil
	if fake.getSpdxIDReturnsOnCall == nil {
		fake.getSpdxIDReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getSpdxIDReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetSpecType() string {
	fake.getSpecTypeMutex.Lock()
	ret, specificReturn := fake.getSpecTypeReturnsOnCall[len(fake.getSpecTypeArgsForCall)]
	fake.getSpecTypeArgsForCall = append(fake.getSpecTypeArgsForCall, struct {
	}{})
	stub := fake.GetSpecTypeStub
	fakeReturns := fake.getSpecTypeReturns
	fake.recordInvocation("GetSpecType", []interface{}{})
	fake.getSpecTypeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpec) GetSpecTypeCallCount() int {
	fake.getSpecTypeMutex.RLock()
	defer fake.getSpecTypeMutex.RUnlock()
	return len(fake.getSpecTypeArgsForCall)
}

func (fake *FakeSpec) GetSpecTypeCalls(stub func() string) {
	fake.getSpecTypeMutex.Lock()
	defer fake.getSpecTypeMutex.Unlock()
	fake.GetSpecTypeStub = stub
}

func (fake *FakeSpec) GetSpecTypeReturns(result1 string) {
	fake.getSpecTypeMutex.Lock()
	defer fake.getSpecTypeMutex.Unlock()
	fake.GetSpecTypeStub = nil
	fake.getSpecTypeReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetSpecTypeReturnsOnCall(i int, result1 string) {
	fake.getSpecTypeMutex.Lock()
	defer fake.getSpecTypeMutex.Unlock()
	fake.GetSpecTypeStub = nil
	if fake.getSpecTypeReturnsOnCall == nil {
		fake.getSpecTypeReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getSpecTypeReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetURI() string {
	fake.getURIMutex.Lock()
	ret, specificReturn := fake.getURIReturnsOnCall[len(fake.getURIArgsForCall)]
	fake.getURIArgsForCall = append(fake.getURIArgsForCall, struct {
	}{})
	stub := fake.GetURIStub
	fakeReturns := fake.getURIReturns
	fake.recordInvocation("GetURI", []interface{}{})
	fake.getURIMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpec) GetURICallCount() int {
	fake.getURIMutex.RLock()
	defer fake.getURIMutex.RUnlock()
	return len(fake.getURIArgsForCall)
}

func (fake *FakeSpec) GetURICalls(stub func() string) {
	fake.getURIMutex.Lock()
	defer fake.getURIMutex.Unlock()
	fake.GetURIStub = stub
}

func (fake *FakeSpec) GetURIReturns(result1 string) {
	fake.getURIMutex.Lock()
	defer fake.getURIMutex.Unlock()
	fake.GetURIStub = nil
	fake.getURIReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetURIReturnsOnCall(i int, result1 string) {
	fake.getURIMutex.Lock()
	defer fake.getURIMutex.Unlock()
	fake.GetURIStub = nil
	if fake.getURIReturnsOnCall == nil {
		fake.getURIReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getURIReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetVersion() string {
	fake.getVersionMutex.Lock()
	ret, specificReturn := fake.getVersionReturnsOnCall[len(fake.getVersionArgsForCall)]
	fake.getVersionArgsForCall = append(fake.getVersionArgsForCall, struct {
	}{})
	stub := fake.GetVersionStub
	fakeReturns := fake.getVersionReturns
	fake.recordInvocation("GetVersion", []interface{}{})
	fake.getVersionMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpec) GetVersionCallCount() int {
	fake.getVersionMutex.RLock()
	defer fake.getVersionMutex.RUnlock()
	return len(fake.getVersionArgsForCall)
}

func (fake *FakeSpec) GetVersionCalls(stub func() string) {
	fake.getVersionMutex.Lock()
	defer fake.getVersionMutex.Unlock()
	fake.GetVersionStub = stub
}

func (fake *FakeSpec) GetVersionReturns(result1 string) {
	fake.getVersionMutex.Lock()
	defer fake.getVersionMutex.Unlock()
	fake.GetVersionStub = nil
	fake.getVersionReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) GetVersionReturnsOnCall(i int, result1 string) {
	fake.getVersionMutex.Lock()
	defer fake.getVersionMutex.Unlock()
	fake.GetVersionStub = nil
	if fake.getVersionReturnsOnCall == nil {
		fake.getVersionReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getVersionReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeSpec) Parsable() bool {
	fake.parsableMutex.Lock()
	ret, specificReturn := fake.parsableReturnsOnCall[len(fake.parsableArgsForCall)]
	fake.parsableArgsForCall = append(fake.parsableArgsForCall, struct {
	}{})
	stub := fake.ParsableStub
	fakeReturns := fake.parsableReturns
	fake.recordInvocation("Parsable", []interface{}{})
	fake.parsableMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpec) ParsableCallCount() int {
	fake.parsableMutex.RLock()
	defer fake.parsableMutex.RUnlock()
	return len(fake.parsableArgsForCall)
}

func (fake *FakeSpec) ParsableCalls(stub func() bool) {
	fake.parsableMutex.Lock()
	defer fake.parsableMutex.Unlock()
	fake.ParsableStub = stub
}

func (fake *FakeSpec) ParsableReturns(result1 bool) {
	fake.parsableMutex.Lock()
	defer fake.parsableMutex.Unlock()
	fake.ParsableStub = nil
	fake.parsableReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeSpec) ParsableReturnsOnCall(i int, result1 bool) {
	fake.parsableMutex.Lock()
	defer fake.parsableMutex.Unlock()
	fake.ParsableStub = nil
	if fake.parsableReturnsOnCall == nil {
		fake.parsableReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.parsableReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeSpec) RequiredFields() bool {
	fake.requiredFieldsMutex.Lock()
	ret, specificReturn := fake.requiredFieldsReturnsOnCall[len(fake.requiredFieldsArgsForCall)]
	fake.requiredFieldsArgsForCall = append(fake.requiredFieldsArgsForCall, struct {
	}{})
	stub := fake.RequiredFieldsStub
	fakeReturns := fake.requiredFieldsReturns
	fake.recordInvocation("RequiredFields", []interface{}{})
	fake.requiredFieldsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpec) RequiredFieldsCallCount() int {
	fake.requiredFieldsMutex.RLock()
	defer fake.requiredFieldsMutex.RUnlock()
	return len(fake.requiredFieldsArgsForCall)
}

func (fake *FakeSpec) RequiredFieldsCalls(stub func() bool) {
	fake.requiredFieldsMutex.Lock()
	defer fake.requiredFieldsMutex.Unlock()
	fake.RequiredFieldsStub = stub
}

func (fake *FakeSpec) RequiredFieldsReturns(result1 bool) {
	fake.requiredFieldsMutex.Lock()
	defer fake.requiredFieldsMutex.Unlock()
	fake.RequiredFieldsStub = nil
	fake.requiredFieldsReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeSpec) RequiredFieldsReturnsOnCall(i int, result1 bool) {
	fake.requiredFieldsMutex.Lock()
	defer fake.requiredFieldsMutex.Unlock()
	fake.RequiredFieldsStub = nil
	if fake.requiredFieldsReturnsOnCall == nil {
		fake.requiredFieldsReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.requiredFieldsReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeSpec) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSpec) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sbom.Spec = new(FakeSpec)
