// Code generated by counterfeiter. DO NOT EDIT.
package sbomfakes

import (
	"sync"

	"github.com/interlynk-io/sbomqs/v2/pkg/sbom"
)

type FakeGetContact struct {
	GetEmailStub        func() string
	getEmailMutex       sync.RWMutex
	getEmailArgsForCall []struct {
	}
	getEmailReturns struct {
		result1 string
	}
	getEmailReturnsOnCall map[int]struct {
		result1 string
	}
	GetNameStub        func() string
	getNameMutex       sync.RWMutex
	getNameArgsForCall []struct {
	}
	getNameReturns struct {
		result1 string
	}
	getNameReturnsOnCall map[int]struct {
		result1 string
	}
	GetPhoneStub        func() string
	getPhoneMutex       sync.RWMutex
	getPhoneArgsForCall []struct {
	}
	getPhoneReturns struct {
		result1 string
	}
	getPhoneReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGetContact) GetEmail() string {
	fake.getEmailMutex.Lock()
	ret, specificReturn := fake.getEmailReturnsOnCall[len(fake.getEmailArgsForCall)]
	fake.getEmailArgsForCall = append(fake.getEmailArgsForCall, struct {
	}{})
	stub := fake.GetEmailStub
	fakeReturns := fake.getEmailReturns
	fake.recordInvocation("GetEmail", []interface{}{})
	fake.getEmailMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetContact) GetEmailCallCount() int {
	fake.getEmailMutex.RLock()
	defer fake.getEmailMutex.RUnlock()
	return len(fake.getEmailArgsForCall)
}

func (fake *FakeGetContact) GetEmailCalls(stub func() string) {
	fake.getEmailMutex.Lock()
	defer fake.getEmailMutex.Unlock()
	fake.GetEmailStub = stub
}

func (fake *FakeGetContact) GetEmailReturns(result1 string) {
	fake.getEmailMutex.Lock()
	defer fake.getEmailMutex.Unlock()
	fake.GetEmailStub = nil
	fake.getEmailReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetContact) GetEmailReturnsOnCall(i int, result1 string) {
	fake.getEmailMutex.Lock()
	defer fake.getEmailMutex.Unlock()
	fake.GetEmailStub = nil
	if fake.getEmailReturnsOnCall == nil {
		fake.getEmailReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getEmailReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetContact) GetName() string {
	fake.getNameMutex.Lock()
	ret, specificReturn := fake.getNameReturnsOnCall[len(fake.getNameArgsForCall)]
	fake.getNameArgsForCall = append(fake.getNameArgsForCall, struct {
	}{})
	stub := fake.GetNameStub
	fakeReturns := fake.getNameReturns
	fake.recordInvocation("GetName", []interface{}{})
	fake.getNameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetContact) GetNameCallCount() int {
	fake.getNameMutex.RLock()
	defer fake.getNameMutex.RUnlock()
	return len(fake.getNameArgsForCall)
}

func (fake *FakeGetContact) GetNameCalls(stub func() string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = stub
}

func (fake *FakeGetContact) GetNameReturns(result1 string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = nil
	fake.getNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetContact) GetNameReturnsOnCall(i int, result1 string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = nil
	if fake.getNameReturnsOnCall == nil {
		fake.getNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetContact) GetPhone() string {
	fake.getPhoneMutex.Lock()
	ret, specificReturn := fake.getPhoneReturnsOnCall[len(fake.getPhoneArgsForCall)]
	fake.getPhoneArgsForCall = append(fake.getPhoneArgsForCall, struct {
	}{})
	stub := fake.GetPhoneStub
	fakeReturns := fake.getPhoneReturns
	fake.recordInvocation("GetPhone", []interface{}{})
	fake.getPhoneMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetContact) GetPhoneCallCount() int {
	fake.getPhoneMutex.RLock()
	defer fake.getPhoneMutex.RUnlock()
	return len(fake.getPhoneArgsForCall)
}

func (fake *FakeGetContact) GetPhoneCalls(stub func() string) {
	fake.getPhoneMutex.Lock()
	defer fake.getPhoneMutex.Unlock()
	fake.GetPhoneStub = stub
}

func (fake *FakeGetContact) GetPhoneReturns(result1 string) {
	fake.getPhoneMutex.Lock()
	defer fake.getPhoneMutex.Unlock()
	fake.GetPhoneStub = nil
	fake.getPhoneReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetContact) GetPhoneReturnsOnCall(i int, result1 string) {
	fake.getPhoneMutex.Lock()
	defer fake.getPhoneMutex.Unlock()
	fake.GetPhoneStub = nil
	if fake.getPhoneReturnsOnCall == nil {
		fake.getPhoneReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getPhoneReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetContact) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGetContact) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sbom.GetContact = new(FakeGetContact)
