// Code generated by counterfeiter. DO NOT EDIT.
package sbomfakes

import (
	"sync"

	"github.com/interlynk-io/sbomqs/pkg/sbom"
)

type FakeGetRelation struct {
	GetFromStub        func() string
	getFromMutex       sync.RWMutex
	getFromArgsForCall []struct {
	}
	getFromReturns struct {
		result1 string
	}
	getFromReturnsOnCall map[int]struct {
		result1 string
	}
	GetToStub        func() string
	getToMutex       sync.RWMutex
	getToArgsForCall []struct {
	}
	getToReturns struct {
		result1 string
	}
	getToReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGetRelation) GetFrom() string {
	fake.getFromMutex.Lock()
	ret, specificReturn := fake.getFromReturnsOnCall[len(fake.getFromArgsForCall)]
	fake.getFromArgsForCall = append(fake.getFromArgsForCall, struct {
	}{})
	stub := fake.GetFromStub
	fakeReturns := fake.getFromReturns
	fake.recordInvocation("GetFrom", []interface{}{})
	fake.getFromMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetRelation) GetFromCallCount() int {
	fake.getFromMutex.RLock()
	defer fake.getFromMutex.RUnlock()
	return len(fake.getFromArgsForCall)
}

func (fake *FakeGetRelation) GetFromCalls(stub func() string) {
	fake.getFromMutex.Lock()
	defer fake.getFromMutex.Unlock()
	fake.GetFromStub = stub
}

func (fake *FakeGetRelation) GetFromReturns(result1 string) {
	fake.getFromMutex.Lock()
	defer fake.getFromMutex.Unlock()
	fake.GetFromStub = nil
	fake.getFromReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetRelation) GetFromReturnsOnCall(i int, result1 string) {
	fake.getFromMutex.Lock()
	defer fake.getFromMutex.Unlock()
	fake.GetFromStub = nil
	if fake.getFromReturnsOnCall == nil {
		fake.getFromReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getFromReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetRelation) GetTo() string {
	fake.getToMutex.Lock()
	ret, specificReturn := fake.getToReturnsOnCall[len(fake.getToArgsForCall)]
	fake.getToArgsForCall = append(fake.getToArgsForCall, struct {
	}{})
	stub := fake.GetToStub
	fakeReturns := fake.getToReturns
	fake.recordInvocation("GetTo", []interface{}{})
	fake.getToMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetRelation) GetToCallCount() int {
	fake.getToMutex.RLock()
	defer fake.getToMutex.RUnlock()
	return len(fake.getToArgsForCall)
}

func (fake *FakeGetRelation) GetToCalls(stub func() string) {
	fake.getToMutex.Lock()
	defer fake.getToMutex.Unlock()
	fake.GetToStub = stub
}

func (fake *FakeGetRelation) GetToReturns(result1 string) {
	fake.getToMutex.Lock()
	defer fake.getToMutex.Unlock()
	fake.GetToStub = nil
	fake.getToReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetRelation) GetToReturnsOnCall(i int, result1 string) {
	fake.getToMutex.Lock()
	defer fake.getToMutex.Unlock()
	fake.GetToStub = nil
	if fake.getToReturnsOnCall == nil {
		fake.getToReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getToReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetRelation) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGetRelation) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sbom.GetRelation = new(FakeGetRelation)
