// Code generated by counterfeiter. DO NOT EDIT.
package sbomfakes

import (
	"sync"

	"github.com/interlynk-io/sbomqs/v2/pkg/sbom"
)

type FakeGetExternalReference struct {
	GetRefLocatorStub        func() string
	getRefLocatorMutex       sync.RWMutex
	getRefLocatorArgsForCall []struct {
	}
	getRefLocatorReturns struct {
		result1 string
	}
	getRefLocatorReturnsOnCall map[int]struct {
		result1 string
	}
	GetRefTypeStub        func() string
	getRefTypeMutex       sync.RWMutex
	getRefTypeArgsForCall []struct {
	}
	getRefTypeReturns struct {
		result1 string
	}
	getRefTypeReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGetExternalReference) GetRefLocator() string {
	fake.getRefLocatorMutex.Lock()
	ret, specificReturn := fake.getRefLocatorReturnsOnCall[len(fake.getRefLocatorArgsForCall)]
	fake.getRefLocatorArgsForCall = append(fake.getRefLocatorArgsForCall, struct {
	}{})
	stub := fake.GetRefLocatorStub
	fakeReturns := fake.getRefLocatorReturns
	fake.recordInvocation("GetRefLocator", []interface{}{})
	fake.getRefLocatorMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetExternalReference) GetRefLocatorCallCount() int {
	fake.getRefLocatorMutex.RLock()
	defer fake.getRefLocatorMutex.RUnlock()
	return len(fake.getRefLocatorArgsForCall)
}

func (fake *FakeGetExternalReference) GetRefLocatorCalls(stub func() string) {
	fake.getRefLocatorMutex.Lock()
	defer fake.getRefLocatorMutex.Unlock()
	fake.GetRefLocatorStub = stub
}

func (fake *FakeGetExternalReference) GetRefLocatorReturns(result1 string) {
	fake.getRefLocatorMutex.Lock()
	defer fake.getRefLocatorMutex.Unlock()
	fake.GetRefLocatorStub = nil
	fake.getRefLocatorReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetExternalReference) GetRefLocatorReturnsOnCall(i int, result1 string) {
	fake.getRefLocatorMutex.Lock()
	defer fake.getRefLocatorMutex.Unlock()
	fake.GetRefLocatorStub = nil
	if fake.getRefLocatorReturnsOnCall == nil {
		fake.getRefLocatorReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getRefLocatorReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetExternalReference) GetRefType() string {
	fake.getRefTypeMutex.Lock()
	ret, specificReturn := fake.getRefTypeReturnsOnCall[len(fake.getRefTypeArgsForCall)]
	fake.getRefTypeArgsForCall = append(fake.getRefTypeArgsForCall, struct {
	}{})
	stub := fake.GetRefTypeStub
	fakeReturns := fake.getRefTypeReturns
	fake.recordInvocation("GetRefType", []interface{}{})
	fake.getRefTypeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetExternalReference) GetRefTypeCallCount() int {
	fake.getRefTypeMutex.RLock()
	defer fake.getRefTypeMutex.RUnlock()
	return len(fake.getRefTypeArgsForCall)
}

func (fake *FakeGetExternalReference) GetRefTypeCalls(stub func() string) {
	fake.getRefTypeMutex.Lock()
	defer fake.getRefTypeMutex.Unlock()
	fake.GetRefTypeStub = stub
}

func (fake *FakeGetExternalReference) GetRefTypeReturns(result1 string) {
	fake.getRefTypeMutex.Lock()
	defer fake.getRefTypeMutex.Unlock()
	fake.GetRefTypeStub = nil
	fake.getRefTypeReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetExternalReference) GetRefTypeReturnsOnCall(i int, result1 string) {
	fake.getRefTypeMutex.Lock()
	defer fake.getRefTypeMutex.Unlock()
	fake.GetRefTypeStub = nil
	if fake.getRefTypeReturnsOnCall == nil {
		fake.getRefTypeReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getRefTypeReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetExternalReference) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGetExternalReference) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sbom.GetExternalReference = new(FakeGetExternalReference)
