// Code generated by counterfeiter. DO NOT EDIT.
package sbomfakes

import (
	"sync"

	"github.com/interlynk-io/sbomqs/pkg/cpe"
	"github.com/interlynk-io/sbomqs/pkg/licenses"
	"github.com/interlynk-io/sbomqs/pkg/omniborid"
	"github.com/interlynk-io/sbomqs/pkg/purl"
	"github.com/interlynk-io/sbomqs/pkg/sbom"
	"github.com/interlynk-io/sbomqs/pkg/swhid"
	"github.com/interlynk-io/sbomqs/pkg/swid"
)

type FakeGetComponent struct {
	AuthorsStub        func() []sbom.GetAuthor
	authorsMutex       sync.RWMutex
	authorsArgsForCall []struct {
	}
	authorsReturns struct {
		result1 []sbom.GetAuthor
	}
	authorsReturnsOnCall map[int]struct {
		result1 []sbom.GetAuthor
	}
	ConcludedLicensesStub        func() []licenses.License
	concludedLicensesMutex       sync.RWMutex
	concludedLicensesArgsForCall []struct {
	}
	concludedLicensesReturns struct {
		result1 []licenses.License
	}
	concludedLicensesReturnsOnCall map[int]struct {
		result1 []licenses.License
	}
	CountOfDependenciesStub        func() int
	countOfDependenciesMutex       sync.RWMutex
	countOfDependenciesArgsForCall []struct {
	}
	countOfDependenciesReturns struct {
		result1 int
	}
	countOfDependenciesReturnsOnCall map[int]struct {
		result1 int
	}
	DeclaredLicensesStub        func() []licenses.License
	declaredLicensesMutex       sync.RWMutex
	declaredLicensesArgsForCall []struct {
	}
	declaredLicensesReturns struct {
		result1 []licenses.License
	}
	declaredLicensesReturnsOnCall map[int]struct {
		result1 []licenses.License
	}
	ExternalReferencesStub        func() []sbom.GetExternalReference
	externalReferencesMutex       sync.RWMutex
	externalReferencesArgsForCall []struct {
	}
	externalReferencesReturns struct {
		result1 []sbom.GetExternalReference
	}
	externalReferencesReturnsOnCall map[int]struct {
		result1 []sbom.GetExternalReference
	}
	GetChecksumsStub        func() []sbom.GetChecksum
	getChecksumsMutex       sync.RWMutex
	getChecksumsArgsForCall []struct {
	}
	getChecksumsReturns struct {
		result1 []sbom.GetChecksum
	}
	getChecksumsReturnsOnCall map[int]struct {
		result1 []sbom.GetChecksum
	}
	GetCompositionStub        func(string) string
	getCompositionMutex       sync.RWMutex
	getCompositionArgsForCall []struct {
		arg1 string
	}
	getCompositionReturns struct {
		result1 string
	}
	getCompositionReturnsOnCall map[int]struct {
		result1 string
	}
	GetCopyRightStub        func() string
	getCopyRightMutex       sync.RWMutex
	getCopyRightArgsForCall []struct {
	}
	getCopyRightReturns struct {
		result1 string
	}
	getCopyRightReturnsOnCall map[int]struct {
		result1 string
	}
	GetCpesStub        func() []cpe.CPE
	getCpesMutex       sync.RWMutex
	getCpesArgsForCall []struct {
	}
	getCpesReturns struct {
		result1 []cpe.CPE
	}
	getCpesReturnsOnCall map[int]struct {
		result1 []cpe.CPE
	}
	GetDownloadLocationURLStub        func() string
	getDownloadLocationURLMutex       sync.RWMutex
	getDownloadLocationURLArgsForCall []struct {
	}
	getDownloadLocationURLReturns struct {
		result1 string
	}
	getDownloadLocationURLReturnsOnCall map[int]struct {
		result1 string
	}
	GetFileAnalyzedStub        func() bool
	getFileAnalyzedMutex       sync.RWMutex
	getFileAnalyzedArgsForCall []struct {
	}
	getFileAnalyzedReturns struct {
		result1 bool
	}
	getFileAnalyzedReturnsOnCall map[int]struct {
		result1 bool
	}
	GetIDStub        func() string
	getIDMutex       sync.RWMutex
	getIDArgsForCall []struct {
	}
	getIDReturns struct {
		result1 string
	}
	getIDReturnsOnCall map[int]struct {
		result1 string
	}
	GetLicensesStub        func() []licenses.License
	getLicensesMutex       sync.RWMutex
	getLicensesArgsForCall []struct {
	}
	getLicensesReturns struct {
		result1 []licenses.License
	}
	getLicensesReturnsOnCall map[int]struct {
		result1 []licenses.License
	}
	GetNameStub        func() string
	getNameMutex       sync.RWMutex
	getNameArgsForCall []struct {
	}
	getNameReturns struct {
		result1 string
	}
	getNameReturnsOnCall map[int]struct {
		result1 string
	}
	GetPackageLicenseConcludedStub        func() string
	getPackageLicenseConcludedMutex       sync.RWMutex
	getPackageLicenseConcludedArgsForCall []struct {
	}
	getPackageLicenseConcludedReturns struct {
		result1 string
	}
	getPackageLicenseConcludedReturnsOnCall map[int]struct {
		result1 string
	}
	GetPackageLicenseDeclaredStub        func() string
	getPackageLicenseDeclaredMutex       sync.RWMutex
	getPackageLicenseDeclaredArgsForCall []struct {
	}
	getPackageLicenseDeclaredReturns struct {
		result1 string
	}
	getPackageLicenseDeclaredReturnsOnCall map[int]struct {
		result1 string
	}
	GetPrimaryCompInfoStub        func() sbom.GetPrimaryComp
	getPrimaryCompInfoMutex       sync.RWMutex
	getPrimaryCompInfoArgsForCall []struct {
	}
	getPrimaryCompInfoReturns struct {
		result1 sbom.GetPrimaryComp
	}
	getPrimaryCompInfoReturnsOnCall map[int]struct {
		result1 sbom.GetPrimaryComp
	}
	GetPurlsStub        func() []purl.PURL
	getPurlsMutex       sync.RWMutex
	getPurlsArgsForCall []struct {
	}
	getPurlsReturns struct {
		result1 []purl.PURL
	}
	getPurlsReturnsOnCall map[int]struct {
		result1 []purl.PURL
	}
	GetSourceCodeURLStub        func() string
	getSourceCodeURLMutex       sync.RWMutex
	getSourceCodeURLArgsForCall []struct {
	}
	getSourceCodeURLReturns struct {
		result1 string
	}
	getSourceCodeURLReturnsOnCall map[int]struct {
		result1 string
	}
	GetSpdxIDStub        func() string
	getSpdxIDMutex       sync.RWMutex
	getSpdxIDArgsForCall []struct {
	}
	getSpdxIDReturns struct {
		result1 string
	}
	getSpdxIDReturnsOnCall map[int]struct {
		result1 string
	}
	GetVersionStub        func() string
	getVersionMutex       sync.RWMutex
	getVersionArgsForCall []struct {
	}
	getVersionReturns struct {
		result1 string
	}
	getVersionReturnsOnCall map[int]struct {
		result1 string
	}
	HasRelationShipsStub        func() bool
	hasRelationShipsMutex       sync.RWMutex
	hasRelationShipsArgsForCall []struct {
	}
	hasRelationShipsReturns struct {
		result1 bool
	}
	hasRelationShipsReturnsOnCall map[int]struct {
		result1 bool
	}
	IsPrimaryComponentStub        func() bool
	isPrimaryComponentMutex       sync.RWMutex
	isPrimaryComponentArgsForCall []struct {
	}
	isPrimaryComponentReturns struct {
		result1 bool
	}
	isPrimaryComponentReturnsOnCall map[int]struct {
		result1 bool
	}
	ManufacturerStub        func() sbom.GetManufacturer
	manufacturerMutex       sync.RWMutex
	manufacturerArgsForCall []struct {
	}
	manufacturerReturns struct {
		result1 sbom.GetManufacturer
	}
	manufacturerReturnsOnCall map[int]struct {
		result1 sbom.GetManufacturer
	}
	OmniborIDsStub        func() []omniborid.OMNIBORID
	omniborIDsMutex       sync.RWMutex
	omniborIDsArgsForCall []struct {
	}
	omniborIDsReturns struct {
		result1 []omniborid.OMNIBORID
	}
	omniborIDsReturnsOnCall map[int]struct {
		result1 []omniborid.OMNIBORID
	}
	PrimaryPurposeStub        func() string
	primaryPurposeMutex       sync.RWMutex
	primaryPurposeArgsForCall []struct {
	}
	primaryPurposeReturns struct {
		result1 string
	}
	primaryPurposeReturnsOnCall map[int]struct {
		result1 string
	}
	RelationShipStateStub        func() string
	relationShipStateMutex       sync.RWMutex
	relationShipStateArgsForCall []struct {
	}
	relationShipStateReturns struct {
		result1 string
	}
	relationShipStateReturnsOnCall map[int]struct {
		result1 string
	}
	RequiredFieldsStub        func() bool
	requiredFieldsMutex       sync.RWMutex
	requiredFieldsArgsForCall []struct {
	}
	requiredFieldsReturns struct {
		result1 bool
	}
	requiredFieldsReturnsOnCall map[int]struct {
		result1 bool
	}
	SourceCodeHashStub        func() string
	sourceCodeHashMutex       sync.RWMutex
	sourceCodeHashArgsForCall []struct {
	}
	sourceCodeHashReturns struct {
		result1 string
	}
	sourceCodeHashReturnsOnCall map[int]struct {
		result1 string
	}
	SuppliersStub        func() sbom.GetSupplier
	suppliersMutex       sync.RWMutex
	suppliersArgsForCall []struct {
	}
	suppliersReturns struct {
		result1 sbom.GetSupplier
	}
	suppliersReturnsOnCall map[int]struct {
		result1 sbom.GetSupplier
	}
	SwhidsStub        func() []swhid.SWHID
	swhidsMutex       sync.RWMutex
	swhidsArgsForCall []struct {
	}
	swhidsReturns struct {
		result1 []swhid.SWHID
	}
	swhidsReturnsOnCall map[int]struct {
		result1 []swhid.SWHID
	}
	SwidsStub        func() []swid.SWID
	swidsMutex       sync.RWMutex
	swidsArgsForCall []struct {
	}
	swidsReturns struct {
		result1 []swid.SWID
	}
	swidsReturnsOnCall map[int]struct {
		result1 []swid.SWID
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGetComponent) Authors() []sbom.GetAuthor {
	fake.authorsMutex.Lock()
	ret, specificReturn := fake.authorsReturnsOnCall[len(fake.authorsArgsForCall)]
	fake.authorsArgsForCall = append(fake.authorsArgsForCall, struct {
	}{})
	stub := fake.AuthorsStub
	fakeReturns := fake.authorsReturns
	fake.recordInvocation("Authors", []interface{}{})
	fake.authorsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) AuthorsCallCount() int {
	fake.authorsMutex.RLock()
	defer fake.authorsMutex.RUnlock()
	return len(fake.authorsArgsForCall)
}

func (fake *FakeGetComponent) AuthorsCalls(stub func() []sbom.GetAuthor) {
	fake.authorsMutex.Lock()
	defer fake.authorsMutex.Unlock()
	fake.AuthorsStub = stub
}

func (fake *FakeGetComponent) AuthorsReturns(result1 []sbom.GetAuthor) {
	fake.authorsMutex.Lock()
	defer fake.authorsMutex.Unlock()
	fake.AuthorsStub = nil
	fake.authorsReturns = struct {
		result1 []sbom.GetAuthor
	}{result1}
}

func (fake *FakeGetComponent) AuthorsReturnsOnCall(i int, result1 []sbom.GetAuthor) {
	fake.authorsMutex.Lock()
	defer fake.authorsMutex.Unlock()
	fake.AuthorsStub = nil
	if fake.authorsReturnsOnCall == nil {
		fake.authorsReturnsOnCall = make(map[int]struct {
			result1 []sbom.GetAuthor
		})
	}
	fake.authorsReturnsOnCall[i] = struct {
		result1 []sbom.GetAuthor
	}{result1}
}

func (fake *FakeGetComponent) ConcludedLicenses() []licenses.License {
	fake.concludedLicensesMutex.Lock()
	ret, specificReturn := fake.concludedLicensesReturnsOnCall[len(fake.concludedLicensesArgsForCall)]
	fake.concludedLicensesArgsForCall = append(fake.concludedLicensesArgsForCall, struct {
	}{})
	stub := fake.ConcludedLicensesStub
	fakeReturns := fake.concludedLicensesReturns
	fake.recordInvocation("ConcludedLicenses", []interface{}{})
	fake.concludedLicensesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) ConcludedLicensesCallCount() int {
	fake.concludedLicensesMutex.RLock()
	defer fake.concludedLicensesMutex.RUnlock()
	return len(fake.concludedLicensesArgsForCall)
}

func (fake *FakeGetComponent) ConcludedLicensesCalls(stub func() []licenses.License) {
	fake.concludedLicensesMutex.Lock()
	defer fake.concludedLicensesMutex.Unlock()
	fake.ConcludedLicensesStub = stub
}

func (fake *FakeGetComponent) ConcludedLicensesReturns(result1 []licenses.License) {
	fake.concludedLicensesMutex.Lock()
	defer fake.concludedLicensesMutex.Unlock()
	fake.ConcludedLicensesStub = nil
	fake.concludedLicensesReturns = struct {
		result1 []licenses.License
	}{result1}
}

func (fake *FakeGetComponent) ConcludedLicensesReturnsOnCall(i int, result1 []licenses.License) {
	fake.concludedLicensesMutex.Lock()
	defer fake.concludedLicensesMutex.Unlock()
	fake.ConcludedLicensesStub = nil
	if fake.concludedLicensesReturnsOnCall == nil {
		fake.concludedLicensesReturnsOnCall = make(map[int]struct {
			result1 []licenses.License
		})
	}
	fake.concludedLicensesReturnsOnCall[i] = struct {
		result1 []licenses.License
	}{result1}
}

func (fake *FakeGetComponent) CountOfDependencies() int {
	fake.countOfDependenciesMutex.Lock()
	ret, specificReturn := fake.countOfDependenciesReturnsOnCall[len(fake.countOfDependenciesArgsForCall)]
	fake.countOfDependenciesArgsForCall = append(fake.countOfDependenciesArgsForCall, struct {
	}{})
	stub := fake.CountOfDependenciesStub
	fakeReturns := fake.countOfDependenciesReturns
	fake.recordInvocation("CountOfDependencies", []interface{}{})
	fake.countOfDependenciesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) CountOfDependenciesCallCount() int {
	fake.countOfDependenciesMutex.RLock()
	defer fake.countOfDependenciesMutex.RUnlock()
	return len(fake.countOfDependenciesArgsForCall)
}

func (fake *FakeGetComponent) CountOfDependenciesCalls(stub func() int) {
	fake.countOfDependenciesMutex.Lock()
	defer fake.countOfDependenciesMutex.Unlock()
	fake.CountOfDependenciesStub = stub
}

func (fake *FakeGetComponent) CountOfDependenciesReturns(result1 int) {
	fake.countOfDependenciesMutex.Lock()
	defer fake.countOfDependenciesMutex.Unlock()
	fake.CountOfDependenciesStub = nil
	fake.countOfDependenciesReturns = struct {
		result1 int
	}{result1}
}

func (fake *FakeGetComponent) CountOfDependenciesReturnsOnCall(i int, result1 int) {
	fake.countOfDependenciesMutex.Lock()
	defer fake.countOfDependenciesMutex.Unlock()
	fake.CountOfDependenciesStub = nil
	if fake.countOfDependenciesReturnsOnCall == nil {
		fake.countOfDependenciesReturnsOnCall = make(map[int]struct {
			result1 int
		})
	}
	fake.countOfDependenciesReturnsOnCall[i] = struct {
		result1 int
	}{result1}
}

func (fake *FakeGetComponent) DeclaredLicenses() []licenses.License {
	fake.declaredLicensesMutex.Lock()
	ret, specificReturn := fake.declaredLicensesReturnsOnCall[len(fake.declaredLicensesArgsForCall)]
	fake.declaredLicensesArgsForCall = append(fake.declaredLicensesArgsForCall, struct {
	}{})
	stub := fake.DeclaredLicensesStub
	fakeReturns := fake.declaredLicensesReturns
	fake.recordInvocation("DeclaredLicenses", []interface{}{})
	fake.declaredLicensesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) DeclaredLicensesCallCount() int {
	fake.declaredLicensesMutex.RLock()
	defer fake.declaredLicensesMutex.RUnlock()
	return len(fake.declaredLicensesArgsForCall)
}

func (fake *FakeGetComponent) DeclaredLicensesCalls(stub func() []licenses.License) {
	fake.declaredLicensesMutex.Lock()
	defer fake.declaredLicensesMutex.Unlock()
	fake.DeclaredLicensesStub = stub
}

func (fake *FakeGetComponent) DeclaredLicensesReturns(result1 []licenses.License) {
	fake.declaredLicensesMutex.Lock()
	defer fake.declaredLicensesMutex.Unlock()
	fake.DeclaredLicensesStub = nil
	fake.declaredLicensesReturns = struct {
		result1 []licenses.License
	}{result1}
}

func (fake *FakeGetComponent) DeclaredLicensesReturnsOnCall(i int, result1 []licenses.License) {
	fake.declaredLicensesMutex.Lock()
	defer fake.declaredLicensesMutex.Unlock()
	fake.DeclaredLicensesStub = nil
	if fake.declaredLicensesReturnsOnCall == nil {
		fake.declaredLicensesReturnsOnCall = make(map[int]struct {
			result1 []licenses.License
		})
	}
	fake.declaredLicensesReturnsOnCall[i] = struct {
		result1 []licenses.License
	}{result1}
}

func (fake *FakeGetComponent) ExternalReferences() []sbom.GetExternalReference {
	fake.externalReferencesMutex.Lock()
	ret, specificReturn := fake.externalReferencesReturnsOnCall[len(fake.externalReferencesArgsForCall)]
	fake.externalReferencesArgsForCall = append(fake.externalReferencesArgsForCall, struct {
	}{})
	stub := fake.ExternalReferencesStub
	fakeReturns := fake.externalReferencesReturns
	fake.recordInvocation("ExternalReferences", []interface{}{})
	fake.externalReferencesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) ExternalReferencesCallCount() int {
	fake.externalReferencesMutex.RLock()
	defer fake.externalReferencesMutex.RUnlock()
	return len(fake.externalReferencesArgsForCall)
}

func (fake *FakeGetComponent) ExternalReferencesCalls(stub func() []sbom.GetExternalReference) {
	fake.externalReferencesMutex.Lock()
	defer fake.externalReferencesMutex.Unlock()
	fake.ExternalReferencesStub = stub
}

func (fake *FakeGetComponent) ExternalReferencesReturns(result1 []sbom.GetExternalReference) {
	fake.externalReferencesMutex.Lock()
	defer fake.externalReferencesMutex.Unlock()
	fake.ExternalReferencesStub = nil
	fake.externalReferencesReturns = struct {
		result1 []sbom.GetExternalReference
	}{result1}
}

func (fake *FakeGetComponent) ExternalReferencesReturnsOnCall(i int, result1 []sbom.GetExternalReference) {
	fake.externalReferencesMutex.Lock()
	defer fake.externalReferencesMutex.Unlock()
	fake.ExternalReferencesStub = nil
	if fake.externalReferencesReturnsOnCall == nil {
		fake.externalReferencesReturnsOnCall = make(map[int]struct {
			result1 []sbom.GetExternalReference
		})
	}
	fake.externalReferencesReturnsOnCall[i] = struct {
		result1 []sbom.GetExternalReference
	}{result1}
}

func (fake *FakeGetComponent) GetChecksums() []sbom.GetChecksum {
	fake.getChecksumsMutex.Lock()
	ret, specificReturn := fake.getChecksumsReturnsOnCall[len(fake.getChecksumsArgsForCall)]
	fake.getChecksumsArgsForCall = append(fake.getChecksumsArgsForCall, struct {
	}{})
	stub := fake.GetChecksumsStub
	fakeReturns := fake.getChecksumsReturns
	fake.recordInvocation("GetChecksums", []interface{}{})
	fake.getChecksumsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetChecksumsCallCount() int {
	fake.getChecksumsMutex.RLock()
	defer fake.getChecksumsMutex.RUnlock()
	return len(fake.getChecksumsArgsForCall)
}

func (fake *FakeGetComponent) GetChecksumsCalls(stub func() []sbom.GetChecksum) {
	fake.getChecksumsMutex.Lock()
	defer fake.getChecksumsMutex.Unlock()
	fake.GetChecksumsStub = stub
}

func (fake *FakeGetComponent) GetChecksumsReturns(result1 []sbom.GetChecksum) {
	fake.getChecksumsMutex.Lock()
	defer fake.getChecksumsMutex.Unlock()
	fake.GetChecksumsStub = nil
	fake.getChecksumsReturns = struct {
		result1 []sbom.GetChecksum
	}{result1}
}

func (fake *FakeGetComponent) GetChecksumsReturnsOnCall(i int, result1 []sbom.GetChecksum) {
	fake.getChecksumsMutex.Lock()
	defer fake.getChecksumsMutex.Unlock()
	fake.GetChecksumsStub = nil
	if fake.getChecksumsReturnsOnCall == nil {
		fake.getChecksumsReturnsOnCall = make(map[int]struct {
			result1 []sbom.GetChecksum
		})
	}
	fake.getChecksumsReturnsOnCall[i] = struct {
		result1 []sbom.GetChecksum
	}{result1}
}

func (fake *FakeGetComponent) GetComposition(arg1 string) string {
	fake.getCompositionMutex.Lock()
	ret, specificReturn := fake.getCompositionReturnsOnCall[len(fake.getCompositionArgsForCall)]
	fake.getCompositionArgsForCall = append(fake.getCompositionArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetCompositionStub
	fakeReturns := fake.getCompositionReturns
	fake.recordInvocation("GetComposition", []interface{}{arg1})
	fake.getCompositionMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetCompositionCallCount() int {
	fake.getCompositionMutex.RLock()
	defer fake.getCompositionMutex.RUnlock()
	return len(fake.getCompositionArgsForCall)
}

func (fake *FakeGetComponent) GetCompositionCalls(stub func(string) string) {
	fake.getCompositionMutex.Lock()
	defer fake.getCompositionMutex.Unlock()
	fake.GetCompositionStub = stub
}

func (fake *FakeGetComponent) GetCompositionArgsForCall(i int) string {
	fake.getCompositionMutex.RLock()
	defer fake.getCompositionMutex.RUnlock()
	argsForCall := fake.getCompositionArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGetComponent) GetCompositionReturns(result1 string) {
	fake.getCompositionMutex.Lock()
	defer fake.getCompositionMutex.Unlock()
	fake.GetCompositionStub = nil
	fake.getCompositionReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetCompositionReturnsOnCall(i int, result1 string) {
	fake.getCompositionMutex.Lock()
	defer fake.getCompositionMutex.Unlock()
	fake.GetCompositionStub = nil
	if fake.getCompositionReturnsOnCall == nil {
		fake.getCompositionReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getCompositionReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetCopyRight() string {
	fake.getCopyRightMutex.Lock()
	ret, specificReturn := fake.getCopyRightReturnsOnCall[len(fake.getCopyRightArgsForCall)]
	fake.getCopyRightArgsForCall = append(fake.getCopyRightArgsForCall, struct {
	}{})
	stub := fake.GetCopyRightStub
	fakeReturns := fake.getCopyRightReturns
	fake.recordInvocation("GetCopyRight", []interface{}{})
	fake.getCopyRightMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetCopyRightCallCount() int {
	fake.getCopyRightMutex.RLock()
	defer fake.getCopyRightMutex.RUnlock()
	return len(fake.getCopyRightArgsForCall)
}

func (fake *FakeGetComponent) GetCopyRightCalls(stub func() string) {
	fake.getCopyRightMutex.Lock()
	defer fake.getCopyRightMutex.Unlock()
	fake.GetCopyRightStub = stub
}

func (fake *FakeGetComponent) GetCopyRightReturns(result1 string) {
	fake.getCopyRightMutex.Lock()
	defer fake.getCopyRightMutex.Unlock()
	fake.GetCopyRightStub = nil
	fake.getCopyRightReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetCopyRightReturnsOnCall(i int, result1 string) {
	fake.getCopyRightMutex.Lock()
	defer fake.getCopyRightMutex.Unlock()
	fake.GetCopyRightStub = nil
	if fake.getCopyRightReturnsOnCall == nil {
		fake.getCopyRightReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getCopyRightReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetCpes() []cpe.CPE {
	fake.getCpesMutex.Lock()
	ret, specificReturn := fake.getCpesReturnsOnCall[len(fake.getCpesArgsForCall)]
	fake.getCpesArgsForCall = append(fake.getCpesArgsForCall, struct {
	}{})
	stub := fake.GetCpesStub
	fakeReturns := fake.getCpesReturns
	fake.recordInvocation("GetCpes", []interface{}{})
	fake.getCpesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetCpesCallCount() int {
	fake.getCpesMutex.RLock()
	defer fake.getCpesMutex.RUnlock()
	return len(fake.getCpesArgsForCall)
}

func (fake *FakeGetComponent) GetCpesCalls(stub func() []cpe.CPE) {
	fake.getCpesMutex.Lock()
	defer fake.getCpesMutex.Unlock()
	fake.GetCpesStub = stub
}

func (fake *FakeGetComponent) GetCpesReturns(result1 []cpe.CPE) {
	fake.getCpesMutex.Lock()
	defer fake.getCpesMutex.Unlock()
	fake.GetCpesStub = nil
	fake.getCpesReturns = struct {
		result1 []cpe.CPE
	}{result1}
}

func (fake *FakeGetComponent) GetCpesReturnsOnCall(i int, result1 []cpe.CPE) {
	fake.getCpesMutex.Lock()
	defer fake.getCpesMutex.Unlock()
	fake.GetCpesStub = nil
	if fake.getCpesReturnsOnCall == nil {
		fake.getCpesReturnsOnCall = make(map[int]struct {
			result1 []cpe.CPE
		})
	}
	fake.getCpesReturnsOnCall[i] = struct {
		result1 []cpe.CPE
	}{result1}
}

func (fake *FakeGetComponent) GetDownloadLocationURL() string {
	fake.getDownloadLocationURLMutex.Lock()
	ret, specificReturn := fake.getDownloadLocationURLReturnsOnCall[len(fake.getDownloadLocationURLArgsForCall)]
	fake.getDownloadLocationURLArgsForCall = append(fake.getDownloadLocationURLArgsForCall, struct {
	}{})
	stub := fake.GetDownloadLocationURLStub
	fakeReturns := fake.getDownloadLocationURLReturns
	fake.recordInvocation("GetDownloadLocationURL", []interface{}{})
	fake.getDownloadLocationURLMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetDownloadLocationURLCallCount() int {
	fake.getDownloadLocationURLMutex.RLock()
	defer fake.getDownloadLocationURLMutex.RUnlock()
	return len(fake.getDownloadLocationURLArgsForCall)
}

func (fake *FakeGetComponent) GetDownloadLocationURLCalls(stub func() string) {
	fake.getDownloadLocationURLMutex.Lock()
	defer fake.getDownloadLocationURLMutex.Unlock()
	fake.GetDownloadLocationURLStub = stub
}

func (fake *FakeGetComponent) GetDownloadLocationURLReturns(result1 string) {
	fake.getDownloadLocationURLMutex.Lock()
	defer fake.getDownloadLocationURLMutex.Unlock()
	fake.GetDownloadLocationURLStub = nil
	fake.getDownloadLocationURLReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetDownloadLocationURLReturnsOnCall(i int, result1 string) {
	fake.getDownloadLocationURLMutex.Lock()
	defer fake.getDownloadLocationURLMutex.Unlock()
	fake.GetDownloadLocationURLStub = nil
	if fake.getDownloadLocationURLReturnsOnCall == nil {
		fake.getDownloadLocationURLReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getDownloadLocationURLReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetFileAnalyzed() bool {
	fake.getFileAnalyzedMutex.Lock()
	ret, specificReturn := fake.getFileAnalyzedReturnsOnCall[len(fake.getFileAnalyzedArgsForCall)]
	fake.getFileAnalyzedArgsForCall = append(fake.getFileAnalyzedArgsForCall, struct {
	}{})
	stub := fake.GetFileAnalyzedStub
	fakeReturns := fake.getFileAnalyzedReturns
	fake.recordInvocation("GetFileAnalyzed", []interface{}{})
	fake.getFileAnalyzedMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetFileAnalyzedCallCount() int {
	fake.getFileAnalyzedMutex.RLock()
	defer fake.getFileAnalyzedMutex.RUnlock()
	return len(fake.getFileAnalyzedArgsForCall)
}

func (fake *FakeGetComponent) GetFileAnalyzedCalls(stub func() bool) {
	fake.getFileAnalyzedMutex.Lock()
	defer fake.getFileAnalyzedMutex.Unlock()
	fake.GetFileAnalyzedStub = stub
}

func (fake *FakeGetComponent) GetFileAnalyzedReturns(result1 bool) {
	fake.getFileAnalyzedMutex.Lock()
	defer fake.getFileAnalyzedMutex.Unlock()
	fake.GetFileAnalyzedStub = nil
	fake.getFileAnalyzedReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGetComponent) GetFileAnalyzedReturnsOnCall(i int, result1 bool) {
	fake.getFileAnalyzedMutex.Lock()
	defer fake.getFileAnalyzedMutex.Unlock()
	fake.GetFileAnalyzedStub = nil
	if fake.getFileAnalyzedReturnsOnCall == nil {
		fake.getFileAnalyzedReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.getFileAnalyzedReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGetComponent) GetID() string {
	fake.getIDMutex.Lock()
	ret, specificReturn := fake.getIDReturnsOnCall[len(fake.getIDArgsForCall)]
	fake.getIDArgsForCall = append(fake.getIDArgsForCall, struct {
	}{})
	stub := fake.GetIDStub
	fakeReturns := fake.getIDReturns
	fake.recordInvocation("GetID", []interface{}{})
	fake.getIDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetIDCallCount() int {
	fake.getIDMutex.RLock()
	defer fake.getIDMutex.RUnlock()
	return len(fake.getIDArgsForCall)
}

func (fake *FakeGetComponent) GetIDCalls(stub func() string) {
	fake.getIDMutex.Lock()
	defer fake.getIDMutex.Unlock()
	fake.GetIDStub = stub
}

func (fake *FakeGetComponent) GetIDReturns(result1 string) {
	fake.getIDMutex.Lock()
	defer fake.getIDMutex.Unlock()
	fake.GetIDStub = nil
	fake.getIDReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetIDReturnsOnCall(i int, result1 string) {
	fake.getIDMutex.Lock()
	defer fake.getIDMutex.Unlock()
	fake.GetIDStub = nil
	if fake.getIDReturnsOnCall == nil {
		fake.getIDReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getIDReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetLicenses() []licenses.License {
	fake.getLicensesMutex.Lock()
	ret, specificReturn := fake.getLicensesReturnsOnCall[len(fake.getLicensesArgsForCall)]
	fake.getLicensesArgsForCall = append(fake.getLicensesArgsForCall, struct {
	}{})
	stub := fake.GetLicensesStub
	fakeReturns := fake.getLicensesReturns
	fake.recordInvocation("GetLicenses", []interface{}{})
	fake.getLicensesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetLicensesCallCount() int {
	fake.getLicensesMutex.RLock()
	defer fake.getLicensesMutex.RUnlock()
	return len(fake.getLicensesArgsForCall)
}

func (fake *FakeGetComponent) GetLicensesCalls(stub func() []licenses.License) {
	fake.getLicensesMutex.Lock()
	defer fake.getLicensesMutex.Unlock()
	fake.GetLicensesStub = stub
}

func (fake *FakeGetComponent) GetLicensesReturns(result1 []licenses.License) {
	fake.getLicensesMutex.Lock()
	defer fake.getLicensesMutex.Unlock()
	fake.GetLicensesStub = nil
	fake.getLicensesReturns = struct {
		result1 []licenses.License
	}{result1}
}

func (fake *FakeGetComponent) GetLicensesReturnsOnCall(i int, result1 []licenses.License) {
	fake.getLicensesMutex.Lock()
	defer fake.getLicensesMutex.Unlock()
	fake.GetLicensesStub = nil
	if fake.getLicensesReturnsOnCall == nil {
		fake.getLicensesReturnsOnCall = make(map[int]struct {
			result1 []licenses.License
		})
	}
	fake.getLicensesReturnsOnCall[i] = struct {
		result1 []licenses.License
	}{result1}
}

func (fake *FakeGetComponent) GetName() string {
	fake.getNameMutex.Lock()
	ret, specificReturn := fake.getNameReturnsOnCall[len(fake.getNameArgsForCall)]
	fake.getNameArgsForCall = append(fake.getNameArgsForCall, struct {
	}{})
	stub := fake.GetNameStub
	fakeReturns := fake.getNameReturns
	fake.recordInvocation("GetName", []interface{}{})
	fake.getNameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetNameCallCount() int {
	fake.getNameMutex.RLock()
	defer fake.getNameMutex.RUnlock()
	return len(fake.getNameArgsForCall)
}

func (fake *FakeGetComponent) GetNameCalls(stub func() string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = stub
}

func (fake *FakeGetComponent) GetNameReturns(result1 string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = nil
	fake.getNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetNameReturnsOnCall(i int, result1 string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = nil
	if fake.getNameReturnsOnCall == nil {
		fake.getNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetPackageLicenseConcluded() string {
	fake.getPackageLicenseConcludedMutex.Lock()
	ret, specificReturn := fake.getPackageLicenseConcludedReturnsOnCall[len(fake.getPackageLicenseConcludedArgsForCall)]
	fake.getPackageLicenseConcludedArgsForCall = append(fake.getPackageLicenseConcludedArgsForCall, struct {
	}{})
	stub := fake.GetPackageLicenseConcludedStub
	fakeReturns := fake.getPackageLicenseConcludedReturns
	fake.recordInvocation("GetPackageLicenseConcluded", []interface{}{})
	fake.getPackageLicenseConcludedMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetPackageLicenseConcludedCallCount() int {
	fake.getPackageLicenseConcludedMutex.RLock()
	defer fake.getPackageLicenseConcludedMutex.RUnlock()
	return len(fake.getPackageLicenseConcludedArgsForCall)
}

func (fake *FakeGetComponent) GetPackageLicenseConcludedCalls(stub func() string) {
	fake.getPackageLicenseConcludedMutex.Lock()
	defer fake.getPackageLicenseConcludedMutex.Unlock()
	fake.GetPackageLicenseConcludedStub = stub
}

func (fake *FakeGetComponent) GetPackageLicenseConcludedReturns(result1 string) {
	fake.getPackageLicenseConcludedMutex.Lock()
	defer fake.getPackageLicenseConcludedMutex.Unlock()
	fake.GetPackageLicenseConcludedStub = nil
	fake.getPackageLicenseConcludedReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetPackageLicenseConcludedReturnsOnCall(i int, result1 string) {
	fake.getPackageLicenseConcludedMutex.Lock()
	defer fake.getPackageLicenseConcludedMutex.Unlock()
	fake.GetPackageLicenseConcludedStub = nil
	if fake.getPackageLicenseConcludedReturnsOnCall == nil {
		fake.getPackageLicenseConcludedReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getPackageLicenseConcludedReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetPackageLicenseDeclared() string {
	fake.getPackageLicenseDeclaredMutex.Lock()
	ret, specificReturn := fake.getPackageLicenseDeclaredReturnsOnCall[len(fake.getPackageLicenseDeclaredArgsForCall)]
	fake.getPackageLicenseDeclaredArgsForCall = append(fake.getPackageLicenseDeclaredArgsForCall, struct {
	}{})
	stub := fake.GetPackageLicenseDeclaredStub
	fakeReturns := fake.getPackageLicenseDeclaredReturns
	fake.recordInvocation("GetPackageLicenseDeclared", []interface{}{})
	fake.getPackageLicenseDeclaredMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetPackageLicenseDeclaredCallCount() int {
	fake.getPackageLicenseDeclaredMutex.RLock()
	defer fake.getPackageLicenseDeclaredMutex.RUnlock()
	return len(fake.getPackageLicenseDeclaredArgsForCall)
}

func (fake *FakeGetComponent) GetPackageLicenseDeclaredCalls(stub func() string) {
	fake.getPackageLicenseDeclaredMutex.Lock()
	defer fake.getPackageLicenseDeclaredMutex.Unlock()
	fake.GetPackageLicenseDeclaredStub = stub
}

func (fake *FakeGetComponent) GetPackageLicenseDeclaredReturns(result1 string) {
	fake.getPackageLicenseDeclaredMutex.Lock()
	defer fake.getPackageLicenseDeclaredMutex.Unlock()
	fake.GetPackageLicenseDeclaredStub = nil
	fake.getPackageLicenseDeclaredReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetPackageLicenseDeclaredReturnsOnCall(i int, result1 string) {
	fake.getPackageLicenseDeclaredMutex.Lock()
	defer fake.getPackageLicenseDeclaredMutex.Unlock()
	fake.GetPackageLicenseDeclaredStub = nil
	if fake.getPackageLicenseDeclaredReturnsOnCall == nil {
		fake.getPackageLicenseDeclaredReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getPackageLicenseDeclaredReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetPrimaryCompInfo() sbom.GetPrimaryComp {
	fake.getPrimaryCompInfoMutex.Lock()
	ret, specificReturn := fake.getPrimaryCompInfoReturnsOnCall[len(fake.getPrimaryCompInfoArgsForCall)]
	fake.getPrimaryCompInfoArgsForCall = append(fake.getPrimaryCompInfoArgsForCall, struct {
	}{})
	stub := fake.GetPrimaryCompInfoStub
	fakeReturns := fake.getPrimaryCompInfoReturns
	fake.recordInvocation("GetPrimaryCompInfo", []interface{}{})
	fake.getPrimaryCompInfoMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetPrimaryCompInfoCallCount() int {
	fake.getPrimaryCompInfoMutex.RLock()
	defer fake.getPrimaryCompInfoMutex.RUnlock()
	return len(fake.getPrimaryCompInfoArgsForCall)
}

func (fake *FakeGetComponent) GetPrimaryCompInfoCalls(stub func() sbom.GetPrimaryComp) {
	fake.getPrimaryCompInfoMutex.Lock()
	defer fake.getPrimaryCompInfoMutex.Unlock()
	fake.GetPrimaryCompInfoStub = stub
}

func (fake *FakeGetComponent) GetPrimaryCompInfoReturns(result1 sbom.GetPrimaryComp) {
	fake.getPrimaryCompInfoMutex.Lock()
	defer fake.getPrimaryCompInfoMutex.Unlock()
	fake.GetPrimaryCompInfoStub = nil
	fake.getPrimaryCompInfoReturns = struct {
		result1 sbom.GetPrimaryComp
	}{result1}
}

func (fake *FakeGetComponent) GetPrimaryCompInfoReturnsOnCall(i int, result1 sbom.GetPrimaryComp) {
	fake.getPrimaryCompInfoMutex.Lock()
	defer fake.getPrimaryCompInfoMutex.Unlock()
	fake.GetPrimaryCompInfoStub = nil
	if fake.getPrimaryCompInfoReturnsOnCall == nil {
		fake.getPrimaryCompInfoReturnsOnCall = make(map[int]struct {
			result1 sbom.GetPrimaryComp
		})
	}
	fake.getPrimaryCompInfoReturnsOnCall[i] = struct {
		result1 sbom.GetPrimaryComp
	}{result1}
}

func (fake *FakeGetComponent) GetPurls() []purl.PURL {
	fake.getPurlsMutex.Lock()
	ret, specificReturn := fake.getPurlsReturnsOnCall[len(fake.getPurlsArgsForCall)]
	fake.getPurlsArgsForCall = append(fake.getPurlsArgsForCall, struct {
	}{})
	stub := fake.GetPurlsStub
	fakeReturns := fake.getPurlsReturns
	fake.recordInvocation("GetPurls", []interface{}{})
	fake.getPurlsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetPurlsCallCount() int {
	fake.getPurlsMutex.RLock()
	defer fake.getPurlsMutex.RUnlock()
	return len(fake.getPurlsArgsForCall)
}

func (fake *FakeGetComponent) GetPurlsCalls(stub func() []purl.PURL) {
	fake.getPurlsMutex.Lock()
	defer fake.getPurlsMutex.Unlock()
	fake.GetPurlsStub = stub
}

func (fake *FakeGetComponent) GetPurlsReturns(result1 []purl.PURL) {
	fake.getPurlsMutex.Lock()
	defer fake.getPurlsMutex.Unlock()
	fake.GetPurlsStub = nil
	fake.getPurlsReturns = struct {
		result1 []purl.PURL
	}{result1}
}

func (fake *FakeGetComponent) GetPurlsReturnsOnCall(i int, result1 []purl.PURL) {
	fake.getPurlsMutex.Lock()
	defer fake.getPurlsMutex.Unlock()
	fake.GetPurlsStub = nil
	if fake.getPurlsReturnsOnCall == nil {
		fake.getPurlsReturnsOnCall = make(map[int]struct {
			result1 []purl.PURL
		})
	}
	fake.getPurlsReturnsOnCall[i] = struct {
		result1 []purl.PURL
	}{result1}
}

func (fake *FakeGetComponent) GetSourceCodeURL() string {
	fake.getSourceCodeURLMutex.Lock()
	ret, specificReturn := fake.getSourceCodeURLReturnsOnCall[len(fake.getSourceCodeURLArgsForCall)]
	fake.getSourceCodeURLArgsForCall = append(fake.getSourceCodeURLArgsForCall, struct {
	}{})
	stub := fake.GetSourceCodeURLStub
	fakeReturns := fake.getSourceCodeURLReturns
	fake.recordInvocation("GetSourceCodeURL", []interface{}{})
	fake.getSourceCodeURLMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetSourceCodeURLCallCount() int {
	fake.getSourceCodeURLMutex.RLock()
	defer fake.getSourceCodeURLMutex.RUnlock()
	return len(fake.getSourceCodeURLArgsForCall)
}

func (fake *FakeGetComponent) GetSourceCodeURLCalls(stub func() string) {
	fake.getSourceCodeURLMutex.Lock()
	defer fake.getSourceCodeURLMutex.Unlock()
	fake.GetSourceCodeURLStub = stub
}

func (fake *FakeGetComponent) GetSourceCodeURLReturns(result1 string) {
	fake.getSourceCodeURLMutex.Lock()
	defer fake.getSourceCodeURLMutex.Unlock()
	fake.GetSourceCodeURLStub = nil
	fake.getSourceCodeURLReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetSourceCodeURLReturnsOnCall(i int, result1 string) {
	fake.getSourceCodeURLMutex.Lock()
	defer fake.getSourceCodeURLMutex.Unlock()
	fake.GetSourceCodeURLStub = nil
	if fake.getSourceCodeURLReturnsOnCall == nil {
		fake.getSourceCodeURLReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getSourceCodeURLReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetSpdxID() string {
	fake.getSpdxIDMutex.Lock()
	ret, specificReturn := fake.getSpdxIDReturnsOnCall[len(fake.getSpdxIDArgsForCall)]
	fake.getSpdxIDArgsForCall = append(fake.getSpdxIDArgsForCall, struct {
	}{})
	stub := fake.GetSpdxIDStub
	fakeReturns := fake.getSpdxIDReturns
	fake.recordInvocation("GetSpdxID", []interface{}{})
	fake.getSpdxIDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetSpdxIDCallCount() int {
	fake.getSpdxIDMutex.RLock()
	defer fake.getSpdxIDMutex.RUnlock()
	return len(fake.getSpdxIDArgsForCall)
}

func (fake *FakeGetComponent) GetSpdxIDCalls(stub func() string) {
	fake.getSpdxIDMutex.Lock()
	defer fake.getSpdxIDMutex.Unlock()
	fake.GetSpdxIDStub = stub
}

func (fake *FakeGetComponent) GetSpdxIDReturns(result1 string) {
	fake.getSpdxIDMutex.Lock()
	defer fake.getSpdxIDMutex.Unlock()
	fake.GetSpdxIDStub = nil
	fake.getSpdxIDReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetSpdxIDReturnsOnCall(i int, result1 string) {
	fake.getSpdxIDMutex.Lock()
	defer fake.getSpdxIDMutex.Unlock()
	fake.GetSpdxIDStub = nil
	if fake.getSpdxIDReturnsOnCall == nil {
		fake.getSpdxIDReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getSpdxIDReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetVersion() string {
	fake.getVersionMutex.Lock()
	ret, specificReturn := fake.getVersionReturnsOnCall[len(fake.getVersionArgsForCall)]
	fake.getVersionArgsForCall = append(fake.getVersionArgsForCall, struct {
	}{})
	stub := fake.GetVersionStub
	fakeReturns := fake.getVersionReturns
	fake.recordInvocation("GetVersion", []interface{}{})
	fake.getVersionMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) GetVersionCallCount() int {
	fake.getVersionMutex.RLock()
	defer fake.getVersionMutex.RUnlock()
	return len(fake.getVersionArgsForCall)
}

func (fake *FakeGetComponent) GetVersionCalls(stub func() string) {
	fake.getVersionMutex.Lock()
	defer fake.getVersionMutex.Unlock()
	fake.GetVersionStub = stub
}

func (fake *FakeGetComponent) GetVersionReturns(result1 string) {
	fake.getVersionMutex.Lock()
	defer fake.getVersionMutex.Unlock()
	fake.GetVersionStub = nil
	fake.getVersionReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) GetVersionReturnsOnCall(i int, result1 string) {
	fake.getVersionMutex.Lock()
	defer fake.getVersionMutex.Unlock()
	fake.GetVersionStub = nil
	if fake.getVersionReturnsOnCall == nil {
		fake.getVersionReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getVersionReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) HasRelationShips() bool {
	fake.hasRelationShipsMutex.Lock()
	ret, specificReturn := fake.hasRelationShipsReturnsOnCall[len(fake.hasRelationShipsArgsForCall)]
	fake.hasRelationShipsArgsForCall = append(fake.hasRelationShipsArgsForCall, struct {
	}{})
	stub := fake.HasRelationShipsStub
	fakeReturns := fake.hasRelationShipsReturns
	fake.recordInvocation("HasRelationShips", []interface{}{})
	fake.hasRelationShipsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) HasRelationShipsCallCount() int {
	fake.hasRelationShipsMutex.RLock()
	defer fake.hasRelationShipsMutex.RUnlock()
	return len(fake.hasRelationShipsArgsForCall)
}

func (fake *FakeGetComponent) HasRelationShipsCalls(stub func() bool) {
	fake.hasRelationShipsMutex.Lock()
	defer fake.hasRelationShipsMutex.Unlock()
	fake.HasRelationShipsStub = stub
}

func (fake *FakeGetComponent) HasRelationShipsReturns(result1 bool) {
	fake.hasRelationShipsMutex.Lock()
	defer fake.hasRelationShipsMutex.Unlock()
	fake.HasRelationShipsStub = nil
	fake.hasRelationShipsReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGetComponent) HasRelationShipsReturnsOnCall(i int, result1 bool) {
	fake.hasRelationShipsMutex.Lock()
	defer fake.hasRelationShipsMutex.Unlock()
	fake.HasRelationShipsStub = nil
	if fake.hasRelationShipsReturnsOnCall == nil {
		fake.hasRelationShipsReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.hasRelationShipsReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGetComponent) IsPrimaryComponent() bool {
	fake.isPrimaryComponentMutex.Lock()
	ret, specificReturn := fake.isPrimaryComponentReturnsOnCall[len(fake.isPrimaryComponentArgsForCall)]
	fake.isPrimaryComponentArgsForCall = append(fake.isPrimaryComponentArgsForCall, struct {
	}{})
	stub := fake.IsPrimaryComponentStub
	fakeReturns := fake.isPrimaryComponentReturns
	fake.recordInvocation("IsPrimaryComponent", []interface{}{})
	fake.isPrimaryComponentMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) IsPrimaryComponentCallCount() int {
	fake.isPrimaryComponentMutex.RLock()
	defer fake.isPrimaryComponentMutex.RUnlock()
	return len(fake.isPrimaryComponentArgsForCall)
}

func (fake *FakeGetComponent) IsPrimaryComponentCalls(stub func() bool) {
	fake.isPrimaryComponentMutex.Lock()
	defer fake.isPrimaryComponentMutex.Unlock()
	fake.IsPrimaryComponentStub = stub
}

func (fake *FakeGetComponent) IsPrimaryComponentReturns(result1 bool) {
	fake.isPrimaryComponentMutex.Lock()
	defer fake.isPrimaryComponentMutex.Unlock()
	fake.IsPrimaryComponentStub = nil
	fake.isPrimaryComponentReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGetComponent) IsPrimaryComponentReturnsOnCall(i int, result1 bool) {
	fake.isPrimaryComponentMutex.Lock()
	defer fake.isPrimaryComponentMutex.Unlock()
	fake.IsPrimaryComponentStub = nil
	if fake.isPrimaryComponentReturnsOnCall == nil {
		fake.isPrimaryComponentReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isPrimaryComponentReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGetComponent) Manufacturer() sbom.GetManufacturer {
	fake.manufacturerMutex.Lock()
	ret, specificReturn := fake.manufacturerReturnsOnCall[len(fake.manufacturerArgsForCall)]
	fake.manufacturerArgsForCall = append(fake.manufacturerArgsForCall, struct {
	}{})
	stub := fake.ManufacturerStub
	fakeReturns := fake.manufacturerReturns
	fake.recordInvocation("Manufacturer", []interface{}{})
	fake.manufacturerMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) ManufacturerCallCount() int {
	fake.manufacturerMutex.RLock()
	defer fake.manufacturerMutex.RUnlock()
	return len(fake.manufacturerArgsForCall)
}

func (fake *FakeGetComponent) ManufacturerCalls(stub func() sbom.GetManufacturer) {
	fake.manufacturerMutex.Lock()
	defer fake.manufacturerMutex.Unlock()
	fake.ManufacturerStub = stub
}

func (fake *FakeGetComponent) ManufacturerReturns(result1 sbom.GetManufacturer) {
	fake.manufacturerMutex.Lock()
	defer fake.manufacturerMutex.Unlock()
	fake.ManufacturerStub = nil
	fake.manufacturerReturns = struct {
		result1 sbom.GetManufacturer
	}{result1}
}

func (fake *FakeGetComponent) ManufacturerReturnsOnCall(i int, result1 sbom.GetManufacturer) {
	fake.manufacturerMutex.Lock()
	defer fake.manufacturerMutex.Unlock()
	fake.ManufacturerStub = nil
	if fake.manufacturerReturnsOnCall == nil {
		fake.manufacturerReturnsOnCall = make(map[int]struct {
			result1 sbom.GetManufacturer
		})
	}
	fake.manufacturerReturnsOnCall[i] = struct {
		result1 sbom.GetManufacturer
	}{result1}
}

func (fake *FakeGetComponent) OmniborIDs() []omniborid.OMNIBORID {
	fake.omniborIDsMutex.Lock()
	ret, specificReturn := fake.omniborIDsReturnsOnCall[len(fake.omniborIDsArgsForCall)]
	fake.omniborIDsArgsForCall = append(fake.omniborIDsArgsForCall, struct {
	}{})
	stub := fake.OmniborIDsStub
	fakeReturns := fake.omniborIDsReturns
	fake.recordInvocation("OmniborIDs", []interface{}{})
	fake.omniborIDsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) OmniborIDsCallCount() int {
	fake.omniborIDsMutex.RLock()
	defer fake.omniborIDsMutex.RUnlock()
	return len(fake.omniborIDsArgsForCall)
}

func (fake *FakeGetComponent) OmniborIDsCalls(stub func() []omniborid.OMNIBORID) {
	fake.omniborIDsMutex.Lock()
	defer fake.omniborIDsMutex.Unlock()
	fake.OmniborIDsStub = stub
}

func (fake *FakeGetComponent) OmniborIDsReturns(result1 []omniborid.OMNIBORID) {
	fake.omniborIDsMutex.Lock()
	defer fake.omniborIDsMutex.Unlock()
	fake.OmniborIDsStub = nil
	fake.omniborIDsReturns = struct {
		result1 []omniborid.OMNIBORID
	}{result1}
}

func (fake *FakeGetComponent) OmniborIDsReturnsOnCall(i int, result1 []omniborid.OMNIBORID) {
	fake.omniborIDsMutex.Lock()
	defer fake.omniborIDsMutex.Unlock()
	fake.OmniborIDsStub = nil
	if fake.omniborIDsReturnsOnCall == nil {
		fake.omniborIDsReturnsOnCall = make(map[int]struct {
			result1 []omniborid.OMNIBORID
		})
	}
	fake.omniborIDsReturnsOnCall[i] = struct {
		result1 []omniborid.OMNIBORID
	}{result1}
}

func (fake *FakeGetComponent) PrimaryPurpose() string {
	fake.primaryPurposeMutex.Lock()
	ret, specificReturn := fake.primaryPurposeReturnsOnCall[len(fake.primaryPurposeArgsForCall)]
	fake.primaryPurposeArgsForCall = append(fake.primaryPurposeArgsForCall, struct {
	}{})
	stub := fake.PrimaryPurposeStub
	fakeReturns := fake.primaryPurposeReturns
	fake.recordInvocation("PrimaryPurpose", []interface{}{})
	fake.primaryPurposeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) PrimaryPurposeCallCount() int {
	fake.primaryPurposeMutex.RLock()
	defer fake.primaryPurposeMutex.RUnlock()
	return len(fake.primaryPurposeArgsForCall)
}

func (fake *FakeGetComponent) PrimaryPurposeCalls(stub func() string) {
	fake.primaryPurposeMutex.Lock()
	defer fake.primaryPurposeMutex.Unlock()
	fake.PrimaryPurposeStub = stub
}

func (fake *FakeGetComponent) PrimaryPurposeReturns(result1 string) {
	fake.primaryPurposeMutex.Lock()
	defer fake.primaryPurposeMutex.Unlock()
	fake.PrimaryPurposeStub = nil
	fake.primaryPurposeReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) PrimaryPurposeReturnsOnCall(i int, result1 string) {
	fake.primaryPurposeMutex.Lock()
	defer fake.primaryPurposeMutex.Unlock()
	fake.PrimaryPurposeStub = nil
	if fake.primaryPurposeReturnsOnCall == nil {
		fake.primaryPurposeReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.primaryPurposeReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) RelationShipState() string {
	fake.relationShipStateMutex.Lock()
	ret, specificReturn := fake.relationShipStateReturnsOnCall[len(fake.relationShipStateArgsForCall)]
	fake.relationShipStateArgsForCall = append(fake.relationShipStateArgsForCall, struct {
	}{})
	stub := fake.RelationShipStateStub
	fakeReturns := fake.relationShipStateReturns
	fake.recordInvocation("RelationShipState", []interface{}{})
	fake.relationShipStateMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) RelationShipStateCallCount() int {
	fake.relationShipStateMutex.RLock()
	defer fake.relationShipStateMutex.RUnlock()
	return len(fake.relationShipStateArgsForCall)
}

func (fake *FakeGetComponent) RelationShipStateCalls(stub func() string) {
	fake.relationShipStateMutex.Lock()
	defer fake.relationShipStateMutex.Unlock()
	fake.RelationShipStateStub = stub
}

func (fake *FakeGetComponent) RelationShipStateReturns(result1 string) {
	fake.relationShipStateMutex.Lock()
	defer fake.relationShipStateMutex.Unlock()
	fake.RelationShipStateStub = nil
	fake.relationShipStateReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) RelationShipStateReturnsOnCall(i int, result1 string) {
	fake.relationShipStateMutex.Lock()
	defer fake.relationShipStateMutex.Unlock()
	fake.RelationShipStateStub = nil
	if fake.relationShipStateReturnsOnCall == nil {
		fake.relationShipStateReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.relationShipStateReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) RequiredFields() bool {
	fake.requiredFieldsMutex.Lock()
	ret, specificReturn := fake.requiredFieldsReturnsOnCall[len(fake.requiredFieldsArgsForCall)]
	fake.requiredFieldsArgsForCall = append(fake.requiredFieldsArgsForCall, struct {
	}{})
	stub := fake.RequiredFieldsStub
	fakeReturns := fake.requiredFieldsReturns
	fake.recordInvocation("RequiredFields", []interface{}{})
	fake.requiredFieldsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) RequiredFieldsCallCount() int {
	fake.requiredFieldsMutex.RLock()
	defer fake.requiredFieldsMutex.RUnlock()
	return len(fake.requiredFieldsArgsForCall)
}

func (fake *FakeGetComponent) RequiredFieldsCalls(stub func() bool) {
	fake.requiredFieldsMutex.Lock()
	defer fake.requiredFieldsMutex.Unlock()
	fake.RequiredFieldsStub = stub
}

func (fake *FakeGetComponent) RequiredFieldsReturns(result1 bool) {
	fake.requiredFieldsMutex.Lock()
	defer fake.requiredFieldsMutex.Unlock()
	fake.RequiredFieldsStub = nil
	fake.requiredFieldsReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGetComponent) RequiredFieldsReturnsOnCall(i int, result1 bool) {
	fake.requiredFieldsMutex.Lock()
	defer fake.requiredFieldsMutex.Unlock()
	fake.RequiredFieldsStub = nil
	if fake.requiredFieldsReturnsOnCall == nil {
		fake.requiredFieldsReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.requiredFieldsReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeGetComponent) SourceCodeHash() string {
	fake.sourceCodeHashMutex.Lock()
	ret, specificReturn := fake.sourceCodeHashReturnsOnCall[len(fake.sourceCodeHashArgsForCall)]
	fake.sourceCodeHashArgsForCall = append(fake.sourceCodeHashArgsForCall, struct {
	}{})
	stub := fake.SourceCodeHashStub
	fakeReturns := fake.sourceCodeHashReturns
	fake.recordInvocation("SourceCodeHash", []interface{}{})
	fake.sourceCodeHashMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) SourceCodeHashCallCount() int {
	fake.sourceCodeHashMutex.RLock()
	defer fake.sourceCodeHashMutex.RUnlock()
	return len(fake.sourceCodeHashArgsForCall)
}

func (fake *FakeGetComponent) SourceCodeHashCalls(stub func() string) {
	fake.sourceCodeHashMutex.Lock()
	defer fake.sourceCodeHashMutex.Unlock()
	fake.SourceCodeHashStub = stub
}

func (fake *FakeGetComponent) SourceCodeHashReturns(result1 string) {
	fake.sourceCodeHashMutex.Lock()
	defer fake.sourceCodeHashMutex.Unlock()
	fake.SourceCodeHashStub = nil
	fake.sourceCodeHashReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) SourceCodeHashReturnsOnCall(i int, result1 string) {
	fake.sourceCodeHashMutex.Lock()
	defer fake.sourceCodeHashMutex.Unlock()
	fake.SourceCodeHashStub = nil
	if fake.sourceCodeHashReturnsOnCall == nil {
		fake.sourceCodeHashReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.sourceCodeHashReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetComponent) Suppliers() sbom.GetSupplier {
	fake.suppliersMutex.Lock()
	ret, specificReturn := fake.suppliersReturnsOnCall[len(fake.suppliersArgsForCall)]
	fake.suppliersArgsForCall = append(fake.suppliersArgsForCall, struct {
	}{})
	stub := fake.SuppliersStub
	fakeReturns := fake.suppliersReturns
	fake.recordInvocation("Suppliers", []interface{}{})
	fake.suppliersMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) SuppliersCallCount() int {
	fake.suppliersMutex.RLock()
	defer fake.suppliersMutex.RUnlock()
	return len(fake.suppliersArgsForCall)
}

func (fake *FakeGetComponent) SuppliersCalls(stub func() sbom.GetSupplier) {
	fake.suppliersMutex.Lock()
	defer fake.suppliersMutex.Unlock()
	fake.SuppliersStub = stub
}

func (fake *FakeGetComponent) SuppliersReturns(result1 sbom.GetSupplier) {
	fake.suppliersMutex.Lock()
	defer fake.suppliersMutex.Unlock()
	fake.SuppliersStub = nil
	fake.suppliersReturns = struct {
		result1 sbom.GetSupplier
	}{result1}
}

func (fake *FakeGetComponent) SuppliersReturnsOnCall(i int, result1 sbom.GetSupplier) {
	fake.suppliersMutex.Lock()
	defer fake.suppliersMutex.Unlock()
	fake.SuppliersStub = nil
	if fake.suppliersReturnsOnCall == nil {
		fake.suppliersReturnsOnCall = make(map[int]struct {
			result1 sbom.GetSupplier
		})
	}
	fake.suppliersReturnsOnCall[i] = struct {
		result1 sbom.GetSupplier
	}{result1}
}

func (fake *FakeGetComponent) Swhids() []swhid.SWHID {
	fake.swhidsMutex.Lock()
	ret, specificReturn := fake.swhidsReturnsOnCall[len(fake.swhidsArgsForCall)]
	fake.swhidsArgsForCall = append(fake.swhidsArgsForCall, struct {
	}{})
	stub := fake.SwhidsStub
	fakeReturns := fake.swhidsReturns
	fake.recordInvocation("Swhids", []interface{}{})
	fake.swhidsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) SwhidsCallCount() int {
	fake.swhidsMutex.RLock()
	defer fake.swhidsMutex.RUnlock()
	return len(fake.swhidsArgsForCall)
}

func (fake *FakeGetComponent) SwhidsCalls(stub func() []swhid.SWHID) {
	fake.swhidsMutex.Lock()
	defer fake.swhidsMutex.Unlock()
	fake.SwhidsStub = stub
}

func (fake *FakeGetComponent) SwhidsReturns(result1 []swhid.SWHID) {
	fake.swhidsMutex.Lock()
	defer fake.swhidsMutex.Unlock()
	fake.SwhidsStub = nil
	fake.swhidsReturns = struct {
		result1 []swhid.SWHID
	}{result1}
}

func (fake *FakeGetComponent) SwhidsReturnsOnCall(i int, result1 []swhid.SWHID) {
	fake.swhidsMutex.Lock()
	defer fake.swhidsMutex.Unlock()
	fake.SwhidsStub = nil
	if fake.swhidsReturnsOnCall == nil {
		fake.swhidsReturnsOnCall = make(map[int]struct {
			result1 []swhid.SWHID
		})
	}
	fake.swhidsReturnsOnCall[i] = struct {
		result1 []swhid.SWHID
	}{result1}
}

func (fake *FakeGetComponent) Swids() []swid.SWID {
	fake.swidsMutex.Lock()
	ret, specificReturn := fake.swidsReturnsOnCall[len(fake.swidsArgsForCall)]
	fake.swidsArgsForCall = append(fake.swidsArgsForCall, struct {
	}{})
	stub := fake.SwidsStub
	fakeReturns := fake.swidsReturns
	fake.recordInvocation("Swids", []interface{}{})
	fake.swidsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetComponent) SwidsCallCount() int {
	fake.swidsMutex.RLock()
	defer fake.swidsMutex.RUnlock()
	return len(fake.swidsArgsForCall)
}

func (fake *FakeGetComponent) SwidsCalls(stub func() []swid.SWID) {
	fake.swidsMutex.Lock()
	defer fake.swidsMutex.Unlock()
	fake.SwidsStub = stub
}

func (fake *FakeGetComponent) SwidsReturns(result1 []swid.SWID) {
	fake.swidsMutex.Lock()
	defer fake.swidsMutex.Unlock()
	fake.SwidsStub = nil
	fake.swidsReturns = struct {
		result1 []swid.SWID
	}{result1}
}

func (fake *FakeGetComponent) SwidsReturnsOnCall(i int, result1 []swid.SWID) {
	fake.swidsMutex.Lock()
	defer fake.swidsMutex.Unlock()
	fake.SwidsStub = nil
	if fake.swidsReturnsOnCall == nil {
		fake.swidsReturnsOnCall = make(map[int]struct {
			result1 []swid.SWID
		})
	}
	fake.swidsReturnsOnCall[i] = struct {
		result1 []swid.SWID
	}{result1}
}

func (fake *FakeGetComponent) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGetComponent) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sbom.GetComponent = new(FakeGetComponent)
