// Code generated by counterfeiter. DO NOT EDIT.
package sbomfakes

import (
	"sync"

	"github.com/interlynk-io/sbomqs/v2/pkg/sbom"
)

type FakeGetManufacturer struct {
	GetContactsStub        func() []sbom.Contact
	getContactsMutex       sync.RWMutex
	getContactsArgsForCall []struct {
	}
	getContactsReturns struct {
		result1 []sbom.Contact
	}
	getContactsReturnsOnCall map[int]struct {
		result1 []sbom.Contact
	}
	GetEmailStub        func() string
	getEmailMutex       sync.RWMutex
	getEmailArgsForCall []struct {
	}
	getEmailReturns struct {
		result1 string
	}
	getEmailReturnsOnCall map[int]struct {
		result1 string
	}
	GetNameStub        func() string
	getNameMutex       sync.RWMutex
	getNameArgsForCall []struct {
	}
	getNameReturns struct {
		result1 string
	}
	getNameReturnsOnCall map[int]struct {
		result1 string
	}
	GetURLStub        func() string
	getURLMutex       sync.RWMutex
	getURLArgsForCall []struct {
	}
	getURLReturns struct {
		result1 string
	}
	getURLReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGetManufacturer) GetContacts() []sbom.Contact {
	fake.getContactsMutex.Lock()
	ret, specificReturn := fake.getContactsReturnsOnCall[len(fake.getContactsArgsForCall)]
	fake.getContactsArgsForCall = append(fake.getContactsArgsForCall, struct {
	}{})
	stub := fake.GetContactsStub
	fakeReturns := fake.getContactsReturns
	fake.recordInvocation("GetContacts", []interface{}{})
	fake.getContactsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetManufacturer) GetContactsCallCount() int {
	fake.getContactsMutex.RLock()
	defer fake.getContactsMutex.RUnlock()
	return len(fake.getContactsArgsForCall)
}

func (fake *FakeGetManufacturer) GetContactsCalls(stub func() []sbom.Contact) {
	fake.getContactsMutex.Lock()
	defer fake.getContactsMutex.Unlock()
	fake.GetContactsStub = stub
}

func (fake *FakeGetManufacturer) GetContactsReturns(result1 []sbom.Contact) {
	fake.getContactsMutex.Lock()
	defer fake.getContactsMutex.Unlock()
	fake.GetContactsStub = nil
	fake.getContactsReturns = struct {
		result1 []sbom.Contact
	}{result1}
}

func (fake *FakeGetManufacturer) GetContactsReturnsOnCall(i int, result1 []sbom.Contact) {
	fake.getContactsMutex.Lock()
	defer fake.getContactsMutex.Unlock()
	fake.GetContactsStub = nil
	if fake.getContactsReturnsOnCall == nil {
		fake.getContactsReturnsOnCall = make(map[int]struct {
			result1 []sbom.Contact
		})
	}
	fake.getContactsReturnsOnCall[i] = struct {
		result1 []sbom.Contact
	}{result1}
}

func (fake *FakeGetManufacturer) GetEmail() string {
	fake.getEmailMutex.Lock()
	ret, specificReturn := fake.getEmailReturnsOnCall[len(fake.getEmailArgsForCall)]
	fake.getEmailArgsForCall = append(fake.getEmailArgsForCall, struct {
	}{})
	stub := fake.GetEmailStub
	fakeReturns := fake.getEmailReturns
	fake.recordInvocation("GetEmail", []interface{}{})
	fake.getEmailMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetManufacturer) GetEmailCallCount() int {
	fake.getEmailMutex.RLock()
	defer fake.getEmailMutex.RUnlock()
	return len(fake.getEmailArgsForCall)
}

func (fake *FakeGetManufacturer) GetEmailCalls(stub func() string) {
	fake.getEmailMutex.Lock()
	defer fake.getEmailMutex.Unlock()
	fake.GetEmailStub = stub
}

func (fake *FakeGetManufacturer) GetEmailReturns(result1 string) {
	fake.getEmailMutex.Lock()
	defer fake.getEmailMutex.Unlock()
	fake.GetEmailStub = nil
	fake.getEmailReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetManufacturer) GetEmailReturnsOnCall(i int, result1 string) {
	fake.getEmailMutex.Lock()
	defer fake.getEmailMutex.Unlock()
	fake.GetEmailStub = nil
	if fake.getEmailReturnsOnCall == nil {
		fake.getEmailReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getEmailReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetManufacturer) GetName() string {
	fake.getNameMutex.Lock()
	ret, specificReturn := fake.getNameReturnsOnCall[len(fake.getNameArgsForCall)]
	fake.getNameArgsForCall = append(fake.getNameArgsForCall, struct {
	}{})
	stub := fake.GetNameStub
	fakeReturns := fake.getNameReturns
	fake.recordInvocation("GetName", []interface{}{})
	fake.getNameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetManufacturer) GetNameCallCount() int {
	fake.getNameMutex.RLock()
	defer fake.getNameMutex.RUnlock()
	return len(fake.getNameArgsForCall)
}

func (fake *FakeGetManufacturer) GetNameCalls(stub func() string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = stub
}

func (fake *FakeGetManufacturer) GetNameReturns(result1 string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = nil
	fake.getNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetManufacturer) GetNameReturnsOnCall(i int, result1 string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = nil
	if fake.getNameReturnsOnCall == nil {
		fake.getNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetManufacturer) GetURL() string {
	fake.getURLMutex.Lock()
	ret, specificReturn := fake.getURLReturnsOnCall[len(fake.getURLArgsForCall)]
	fake.getURLArgsForCall = append(fake.getURLArgsForCall, struct {
	}{})
	stub := fake.GetURLStub
	fakeReturns := fake.getURLReturns
	fake.recordInvocation("GetURL", []interface{}{})
	fake.getURLMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetManufacturer) GetURLCallCount() int {
	fake.getURLMutex.RLock()
	defer fake.getURLMutex.RUnlock()
	return len(fake.getURLArgsForCall)
}

func (fake *FakeGetManufacturer) GetURLCalls(stub func() string) {
	fake.getURLMutex.Lock()
	defer fake.getURLMutex.Unlock()
	fake.GetURLStub = stub
}

func (fake *FakeGetManufacturer) GetURLReturns(result1 string) {
	fake.getURLMutex.Lock()
	defer fake.getURLMutex.Unlock()
	fake.GetURLStub = nil
	fake.getURLReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetManufacturer) GetURLReturnsOnCall(i int, result1 string) {
	fake.getURLMutex.Lock()
	defer fake.getURLMutex.Unlock()
	fake.GetURLStub = nil
	if fake.getURLReturnsOnCall == nil {
		fake.getURLReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getURLReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetManufacturer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGetManufacturer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sbom.GetManufacturer = new(FakeGetManufacturer)
