// Code generated by counterfeiter. DO NOT EDIT.
package sbomfakes

import (
	"sync"

	"github.com/interlynk-io/sbomqs/pkg/sbom"
)

type FakeGetChecksum struct {
	GetAlgoStub        func() string
	getAlgoMutex       sync.RWMutex
	getAlgoArgsForCall []struct {
	}
	getAlgoReturns struct {
		result1 string
	}
	getAlgoReturnsOnCall map[int]struct {
		result1 string
	}
	GetContentStub        func() string
	getContentMutex       sync.RWMutex
	getContentArgsForCall []struct {
	}
	getContentReturns struct {
		result1 string
	}
	getContentReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGetChecksum) GetAlgo() string {
	fake.getAlgoMutex.Lock()
	ret, specificReturn := fake.getAlgoReturnsOnCall[len(fake.getAlgoArgsForCall)]
	fake.getAlgoArgsForCall = append(fake.getAlgoArgsForCall, struct {
	}{})
	stub := fake.GetAlgoStub
	fakeReturns := fake.getAlgoReturns
	fake.recordInvocation("GetAlgo", []interface{}{})
	fake.getAlgoMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetChecksum) GetAlgoCallCount() int {
	fake.getAlgoMutex.RLock()
	defer fake.getAlgoMutex.RUnlock()
	return len(fake.getAlgoArgsForCall)
}

func (fake *FakeGetChecksum) GetAlgoCalls(stub func() string) {
	fake.getAlgoMutex.Lock()
	defer fake.getAlgoMutex.Unlock()
	fake.GetAlgoStub = stub
}

func (fake *FakeGetChecksum) GetAlgoReturns(result1 string) {
	fake.getAlgoMutex.Lock()
	defer fake.getAlgoMutex.Unlock()
	fake.GetAlgoStub = nil
	fake.getAlgoReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetChecksum) GetAlgoReturnsOnCall(i int, result1 string) {
	fake.getAlgoMutex.Lock()
	defer fake.getAlgoMutex.Unlock()
	fake.GetAlgoStub = nil
	if fake.getAlgoReturnsOnCall == nil {
		fake.getAlgoReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getAlgoReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetChecksum) GetContent() string {
	fake.getContentMutex.Lock()
	ret, specificReturn := fake.getContentReturnsOnCall[len(fake.getContentArgsForCall)]
	fake.getContentArgsForCall = append(fake.getContentArgsForCall, struct {
	}{})
	stub := fake.GetContentStub
	fakeReturns := fake.getContentReturns
	fake.recordInvocation("GetContent", []interface{}{})
	fake.getContentMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGetChecksum) GetContentCallCount() int {
	fake.getContentMutex.RLock()
	defer fake.getContentMutex.RUnlock()
	return len(fake.getContentArgsForCall)
}

func (fake *FakeGetChecksum) GetContentCalls(stub func() string) {
	fake.getContentMutex.Lock()
	defer fake.getContentMutex.Unlock()
	fake.GetContentStub = stub
}

func (fake *FakeGetChecksum) GetContentReturns(result1 string) {
	fake.getContentMutex.Lock()
	defer fake.getContentMutex.Unlock()
	fake.GetContentStub = nil
	fake.getContentReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetChecksum) GetContentReturnsOnCall(i int, result1 string) {
	fake.getContentMutex.Lock()
	defer fake.getContentMutex.Unlock()
	fake.GetContentStub = nil
	if fake.getContentReturnsOnCall == nil {
		fake.getContentReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getContentReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGetChecksum) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGetChecksum) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sbom.GetChecksum = new(FakeGetChecksum)
