// Code generated by counterfeiter. DO NOT EDIT.
package sbomfakes

import (
	"sync"

	"github.com/interlynk-io/sbomqs/pkg/sbom"
)

type FakeDocument struct {
	AuthorsStub        func() []sbom.GetAuthor
	authorsMutex       sync.RWMutex
	authorsArgsForCall []struct {
	}
	authorsReturns struct {
		result1 []sbom.GetAuthor
	}
	authorsReturnsOnCall map[int]struct {
		result1 []sbom.GetAuthor
	}
	ComponentsStub        func() []sbom.GetComponent
	componentsMutex       sync.RWMutex
	componentsArgsForCall []struct {
	}
	componentsReturns struct {
		result1 []sbom.GetComponent
	}
	componentsReturnsOnCall map[int]struct {
		result1 []sbom.GetComponent
	}
	GetRelationshipsStub        func(string) []string
	getRelationshipsMutex       sync.RWMutex
	getRelationshipsArgsForCall []struct {
		arg1 string
	}
	getRelationshipsReturns struct {
		result1 []string
	}
	getRelationshipsReturnsOnCall map[int]struct {
		result1 []string
	}
	LifecyclesStub        func() []string
	lifecyclesMutex       sync.RWMutex
	lifecyclesArgsForCall []struct {
	}
	lifecyclesReturns struct {
		result1 []string
	}
	lifecyclesReturnsOnCall map[int]struct {
		result1 []string
	}
	LogsStub        func() []string
	logsMutex       sync.RWMutex
	logsArgsForCall []struct {
	}
	logsReturns struct {
		result1 []string
	}
	logsReturnsOnCall map[int]struct {
		result1 []string
	}
	ManufacturerStub        func() sbom.GetManufacturer
	manufacturerMutex       sync.RWMutex
	manufacturerArgsForCall []struct {
	}
	manufacturerReturns struct {
		result1 sbom.GetManufacturer
	}
	manufacturerReturnsOnCall map[int]struct {
		result1 sbom.GetManufacturer
	}
	PrimaryCompStub        func() sbom.GetPrimaryComp
	primaryCompMutex       sync.RWMutex
	primaryCompArgsForCall []struct {
	}
	primaryCompReturns struct {
		result1 sbom.GetPrimaryComp
	}
	primaryCompReturnsOnCall map[int]struct {
		result1 sbom.GetPrimaryComp
	}
	RelationsStub        func() []sbom.GetRelation
	relationsMutex       sync.RWMutex
	relationsArgsForCall []struct {
	}
	relationsReturns struct {
		result1 []sbom.GetRelation
	}
	relationsReturnsOnCall map[int]struct {
		result1 []sbom.GetRelation
	}
	SchemaValidationStub        func() bool
	schemaValidationMutex       sync.RWMutex
	schemaValidationArgsForCall []struct {
	}
	schemaValidationReturns struct {
		result1 bool
	}
	schemaValidationReturnsOnCall map[int]struct {
		result1 bool
	}
	SignatureStub        func() sbom.GetSignature
	signatureMutex       sync.RWMutex
	signatureArgsForCall []struct {
	}
	signatureReturns struct {
		result1 sbom.GetSignature
	}
	signatureReturnsOnCall map[int]struct {
		result1 sbom.GetSignature
	}
	SpecStub        func() sbom.Spec
	specMutex       sync.RWMutex
	specArgsForCall []struct {
	}
	specReturns struct {
		result1 sbom.Spec
	}
	specReturnsOnCall map[int]struct {
		result1 sbom.Spec
	}
	SupplierStub        func() sbom.GetSupplier
	supplierMutex       sync.RWMutex
	supplierArgsForCall []struct {
	}
	supplierReturns struct {
		result1 sbom.GetSupplier
	}
	supplierReturnsOnCall map[int]struct {
		result1 sbom.GetSupplier
	}
	ToolsStub        func() []sbom.GetTool
	toolsMutex       sync.RWMutex
	toolsArgsForCall []struct {
	}
	toolsReturns struct {
		result1 []sbom.GetTool
	}
	toolsReturnsOnCall map[int]struct {
		result1 []sbom.GetTool
	}
	VulnerabilitiesStub        func() []sbom.GetVulnerabilities
	vulnerabilitiesMutex       sync.RWMutex
	vulnerabilitiesArgsForCall []struct {
	}
	vulnerabilitiesReturns struct {
		result1 []sbom.GetVulnerabilities
	}
	vulnerabilitiesReturnsOnCall map[int]struct {
		result1 []sbom.GetVulnerabilities
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDocument) Authors() []sbom.GetAuthor {
	fake.authorsMutex.Lock()
	ret, specificReturn := fake.authorsReturnsOnCall[len(fake.authorsArgsForCall)]
	fake.authorsArgsForCall = append(fake.authorsArgsForCall, struct {
	}{})
	stub := fake.AuthorsStub
	fakeReturns := fake.authorsReturns
	fake.recordInvocation("Authors", []interface{}{})
	fake.authorsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDocument) AuthorsCallCount() int {
	fake.authorsMutex.RLock()
	defer fake.authorsMutex.RUnlock()
	return len(fake.authorsArgsForCall)
}

func (fake *FakeDocument) AuthorsCalls(stub func() []sbom.GetAuthor) {
	fake.authorsMutex.Lock()
	defer fake.authorsMutex.Unlock()
	fake.AuthorsStub = stub
}

func (fake *FakeDocument) AuthorsReturns(result1 []sbom.GetAuthor) {
	fake.authorsMutex.Lock()
	defer fake.authorsMutex.Unlock()
	fake.AuthorsStub = nil
	fake.authorsReturns = struct {
		result1 []sbom.GetAuthor
	}{result1}
}

func (fake *FakeDocument) AuthorsReturnsOnCall(i int, result1 []sbom.GetAuthor) {
	fake.authorsMutex.Lock()
	defer fake.authorsMutex.Unlock()
	fake.AuthorsStub = nil
	if fake.authorsReturnsOnCall == nil {
		fake.authorsReturnsOnCall = make(map[int]struct {
			result1 []sbom.GetAuthor
		})
	}
	fake.authorsReturnsOnCall[i] = struct {
		result1 []sbom.GetAuthor
	}{result1}
}

func (fake *FakeDocument) Components() []sbom.GetComponent {
	fake.componentsMutex.Lock()
	ret, specificReturn := fake.componentsReturnsOnCall[len(fake.componentsArgsForCall)]
	fake.componentsArgsForCall = append(fake.componentsArgsForCall, struct {
	}{})
	stub := fake.ComponentsStub
	fakeReturns := fake.componentsReturns
	fake.recordInvocation("Components", []interface{}{})
	fake.componentsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDocument) ComponentsCallCount() int {
	fake.componentsMutex.RLock()
	defer fake.componentsMutex.RUnlock()
	return len(fake.componentsArgsForCall)
}

func (fake *FakeDocument) ComponentsCalls(stub func() []sbom.GetComponent) {
	fake.componentsMutex.Lock()
	defer fake.componentsMutex.Unlock()
	fake.ComponentsStub = stub
}

func (fake *FakeDocument) ComponentsReturns(result1 []sbom.GetComponent) {
	fake.componentsMutex.Lock()
	defer fake.componentsMutex.Unlock()
	fake.ComponentsStub = nil
	fake.componentsReturns = struct {
		result1 []sbom.GetComponent
	}{result1}
}

func (fake *FakeDocument) ComponentsReturnsOnCall(i int, result1 []sbom.GetComponent) {
	fake.componentsMutex.Lock()
	defer fake.componentsMutex.Unlock()
	fake.ComponentsStub = nil
	if fake.componentsReturnsOnCall == nil {
		fake.componentsReturnsOnCall = make(map[int]struct {
			result1 []sbom.GetComponent
		})
	}
	fake.componentsReturnsOnCall[i] = struct {
		result1 []sbom.GetComponent
	}{result1}
}

func (fake *FakeDocument) GetRelationships(arg1 string) []string {
	fake.getRelationshipsMutex.Lock()
	ret, specificReturn := fake.getRelationshipsReturnsOnCall[len(fake.getRelationshipsArgsForCall)]
	fake.getRelationshipsArgsForCall = append(fake.getRelationshipsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetRelationshipsStub
	fakeReturns := fake.getRelationshipsReturns
	fake.recordInvocation("GetRelationships", []interface{}{arg1})
	fake.getRelationshipsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDocument) GetRelationshipsCallCount() int {
	fake.getRelationshipsMutex.RLock()
	defer fake.getRelationshipsMutex.RUnlock()
	return len(fake.getRelationshipsArgsForCall)
}

func (fake *FakeDocument) GetRelationshipsCalls(stub func(string) []string) {
	fake.getRelationshipsMutex.Lock()
	defer fake.getRelationshipsMutex.Unlock()
	fake.GetRelationshipsStub = stub
}

func (fake *FakeDocument) GetRelationshipsArgsForCall(i int) string {
	fake.getRelationshipsMutex.RLock()
	defer fake.getRelationshipsMutex.RUnlock()
	argsForCall := fake.getRelationshipsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDocument) GetRelationshipsReturns(result1 []string) {
	fake.getRelationshipsMutex.Lock()
	defer fake.getRelationshipsMutex.Unlock()
	fake.GetRelationshipsStub = nil
	fake.getRelationshipsReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeDocument) GetRelationshipsReturnsOnCall(i int, result1 []string) {
	fake.getRelationshipsMutex.Lock()
	defer fake.getRelationshipsMutex.Unlock()
	fake.GetRelationshipsStub = nil
	if fake.getRelationshipsReturnsOnCall == nil {
		fake.getRelationshipsReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.getRelationshipsReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeDocument) Lifecycles() []string {
	fake.lifecyclesMutex.Lock()
	ret, specificReturn := fake.lifecyclesReturnsOnCall[len(fake.lifecyclesArgsForCall)]
	fake.lifecyclesArgsForCall = append(fake.lifecyclesArgsForCall, struct {
	}{})
	stub := fake.LifecyclesStub
	fakeReturns := fake.lifecyclesReturns
	fake.recordInvocation("Lifecycles", []interface{}{})
	fake.lifecyclesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDocument) LifecyclesCallCount() int {
	fake.lifecyclesMutex.RLock()
	defer fake.lifecyclesMutex.RUnlock()
	return len(fake.lifecyclesArgsForCall)
}

func (fake *FakeDocument) LifecyclesCalls(stub func() []string) {
	fake.lifecyclesMutex.Lock()
	defer fake.lifecyclesMutex.Unlock()
	fake.LifecyclesStub = stub
}

func (fake *FakeDocument) LifecyclesReturns(result1 []string) {
	fake.lifecyclesMutex.Lock()
	defer fake.lifecyclesMutex.Unlock()
	fake.LifecyclesStub = nil
	fake.lifecyclesReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeDocument) LifecyclesReturnsOnCall(i int, result1 []string) {
	fake.lifecyclesMutex.Lock()
	defer fake.lifecyclesMutex.Unlock()
	fake.LifecyclesStub = nil
	if fake.lifecyclesReturnsOnCall == nil {
		fake.lifecyclesReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.lifecyclesReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeDocument) Logs() []string {
	fake.logsMutex.Lock()
	ret, specificReturn := fake.logsReturnsOnCall[len(fake.logsArgsForCall)]
	fake.logsArgsForCall = append(fake.logsArgsForCall, struct {
	}{})
	stub := fake.LogsStub
	fakeReturns := fake.logsReturns
	fake.recordInvocation("Logs", []interface{}{})
	fake.logsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDocument) LogsCallCount() int {
	fake.logsMutex.RLock()
	defer fake.logsMutex.RUnlock()
	return len(fake.logsArgsForCall)
}

func (fake *FakeDocument) LogsCalls(stub func() []string) {
	fake.logsMutex.Lock()
	defer fake.logsMutex.Unlock()
	fake.LogsStub = stub
}

func (fake *FakeDocument) LogsReturns(result1 []string) {
	fake.logsMutex.Lock()
	defer fake.logsMutex.Unlock()
	fake.LogsStub = nil
	fake.logsReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeDocument) LogsReturnsOnCall(i int, result1 []string) {
	fake.logsMutex.Lock()
	defer fake.logsMutex.Unlock()
	fake.LogsStub = nil
	if fake.logsReturnsOnCall == nil {
		fake.logsReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.logsReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeDocument) Manufacturer() sbom.GetManufacturer {
	fake.manufacturerMutex.Lock()
	ret, specificReturn := fake.manufacturerReturnsOnCall[len(fake.manufacturerArgsForCall)]
	fake.manufacturerArgsForCall = append(fake.manufacturerArgsForCall, struct {
	}{})
	stub := fake.ManufacturerStub
	fakeReturns := fake.manufacturerReturns
	fake.recordInvocation("Manufacturer", []interface{}{})
	fake.manufacturerMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDocument) ManufacturerCallCount() int {
	fake.manufacturerMutex.RLock()
	defer fake.manufacturerMutex.RUnlock()
	return len(fake.manufacturerArgsForCall)
}

func (fake *FakeDocument) ManufacturerCalls(stub func() sbom.GetManufacturer) {
	fake.manufacturerMutex.Lock()
	defer fake.manufacturerMutex.Unlock()
	fake.ManufacturerStub = stub
}

func (fake *FakeDocument) ManufacturerReturns(result1 sbom.GetManufacturer) {
	fake.manufacturerMutex.Lock()
	defer fake.manufacturerMutex.Unlock()
	fake.ManufacturerStub = nil
	fake.manufacturerReturns = struct {
		result1 sbom.GetManufacturer
	}{result1}
}

func (fake *FakeDocument) ManufacturerReturnsOnCall(i int, result1 sbom.GetManufacturer) {
	fake.manufacturerMutex.Lock()
	defer fake.manufacturerMutex.Unlock()
	fake.ManufacturerStub = nil
	if fake.manufacturerReturnsOnCall == nil {
		fake.manufacturerReturnsOnCall = make(map[int]struct {
			result1 sbom.GetManufacturer
		})
	}
	fake.manufacturerReturnsOnCall[i] = struct {
		result1 sbom.GetManufacturer
	}{result1}
}

func (fake *FakeDocument) PrimaryComp() sbom.GetPrimaryComp {
	fake.primaryCompMutex.Lock()
	ret, specificReturn := fake.primaryCompReturnsOnCall[len(fake.primaryCompArgsForCall)]
	fake.primaryCompArgsForCall = append(fake.primaryCompArgsForCall, struct {
	}{})
	stub := fake.PrimaryCompStub
	fakeReturns := fake.primaryCompReturns
	fake.recordInvocation("PrimaryComp", []interface{}{})
	fake.primaryCompMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDocument) PrimaryCompCallCount() int {
	fake.primaryCompMutex.RLock()
	defer fake.primaryCompMutex.RUnlock()
	return len(fake.primaryCompArgsForCall)
}

func (fake *FakeDocument) PrimaryCompCalls(stub func() sbom.GetPrimaryComp) {
	fake.primaryCompMutex.Lock()
	defer fake.primaryCompMutex.Unlock()
	fake.PrimaryCompStub = stub
}

func (fake *FakeDocument) PrimaryCompReturns(result1 sbom.GetPrimaryComp) {
	fake.primaryCompMutex.Lock()
	defer fake.primaryCompMutex.Unlock()
	fake.PrimaryCompStub = nil
	fake.primaryCompReturns = struct {
		result1 sbom.GetPrimaryComp
	}{result1}
}

func (fake *FakeDocument) PrimaryCompReturnsOnCall(i int, result1 sbom.GetPrimaryComp) {
	fake.primaryCompMutex.Lock()
	defer fake.primaryCompMutex.Unlock()
	fake.PrimaryCompStub = nil
	if fake.primaryCompReturnsOnCall == nil {
		fake.primaryCompReturnsOnCall = make(map[int]struct {
			result1 sbom.GetPrimaryComp
		})
	}
	fake.primaryCompReturnsOnCall[i] = struct {
		result1 sbom.GetPrimaryComp
	}{result1}
}

func (fake *FakeDocument) Relations() []sbom.GetRelation {
	fake.relationsMutex.Lock()
	ret, specificReturn := fake.relationsReturnsOnCall[len(fake.relationsArgsForCall)]
	fake.relationsArgsForCall = append(fake.relationsArgsForCall, struct {
	}{})
	stub := fake.RelationsStub
	fakeReturns := fake.relationsReturns
	fake.recordInvocation("Relations", []interface{}{})
	fake.relationsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDocument) RelationsCallCount() int {
	fake.relationsMutex.RLock()
	defer fake.relationsMutex.RUnlock()
	return len(fake.relationsArgsForCall)
}

func (fake *FakeDocument) RelationsCalls(stub func() []sbom.GetRelation) {
	fake.relationsMutex.Lock()
	defer fake.relationsMutex.Unlock()
	fake.RelationsStub = stub
}

func (fake *FakeDocument) RelationsReturns(result1 []sbom.GetRelation) {
	fake.relationsMutex.Lock()
	defer fake.relationsMutex.Unlock()
	fake.RelationsStub = nil
	fake.relationsReturns = struct {
		result1 []sbom.GetRelation
	}{result1}
}

func (fake *FakeDocument) RelationsReturnsOnCall(i int, result1 []sbom.GetRelation) {
	fake.relationsMutex.Lock()
	defer fake.relationsMutex.Unlock()
	fake.RelationsStub = nil
	if fake.relationsReturnsOnCall == nil {
		fake.relationsReturnsOnCall = make(map[int]struct {
			result1 []sbom.GetRelation
		})
	}
	fake.relationsReturnsOnCall[i] = struct {
		result1 []sbom.GetRelation
	}{result1}
}

func (fake *FakeDocument) SchemaValidation() bool {
	fake.schemaValidationMutex.Lock()
	ret, specificReturn := fake.schemaValidationReturnsOnCall[len(fake.schemaValidationArgsForCall)]
	fake.schemaValidationArgsForCall = append(fake.schemaValidationArgsForCall, struct {
	}{})
	stub := fake.SchemaValidationStub
	fakeReturns := fake.schemaValidationReturns
	fake.recordInvocation("SchemaValidation", []interface{}{})
	fake.schemaValidationMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDocument) SchemaValidationCallCount() int {
	fake.schemaValidationMutex.RLock()
	defer fake.schemaValidationMutex.RUnlock()
	return len(fake.schemaValidationArgsForCall)
}

func (fake *FakeDocument) SchemaValidationCalls(stub func() bool) {
	fake.schemaValidationMutex.Lock()
	defer fake.schemaValidationMutex.Unlock()
	fake.SchemaValidationStub = stub
}

func (fake *FakeDocument) SchemaValidationReturns(result1 bool) {
	fake.schemaValidationMutex.Lock()
	defer fake.schemaValidationMutex.Unlock()
	fake.SchemaValidationStub = nil
	fake.schemaValidationReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeDocument) SchemaValidationReturnsOnCall(i int, result1 bool) {
	fake.schemaValidationMutex.Lock()
	defer fake.schemaValidationMutex.Unlock()
	fake.SchemaValidationStub = nil
	if fake.schemaValidationReturnsOnCall == nil {
		fake.schemaValidationReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.schemaValidationReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeDocument) Signature() sbom.GetSignature {
	fake.signatureMutex.Lock()
	ret, specificReturn := fake.signatureReturnsOnCall[len(fake.signatureArgsForCall)]
	fake.signatureArgsForCall = append(fake.signatureArgsForCall, struct {
	}{})
	stub := fake.SignatureStub
	fakeReturns := fake.signatureReturns
	fake.recordInvocation("Signature", []interface{}{})
	fake.signatureMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDocument) SignatureCallCount() int {
	fake.signatureMutex.RLock()
	defer fake.signatureMutex.RUnlock()
	return len(fake.signatureArgsForCall)
}

func (fake *FakeDocument) SignatureCalls(stub func() sbom.GetSignature) {
	fake.signatureMutex.Lock()
	defer fake.signatureMutex.Unlock()
	fake.SignatureStub = stub
}

func (fake *FakeDocument) SignatureReturns(result1 sbom.GetSignature) {
	fake.signatureMutex.Lock()
	defer fake.signatureMutex.Unlock()
	fake.SignatureStub = nil
	fake.signatureReturns = struct {
		result1 sbom.GetSignature
	}{result1}
}

func (fake *FakeDocument) SignatureReturnsOnCall(i int, result1 sbom.GetSignature) {
	fake.signatureMutex.Lock()
	defer fake.signatureMutex.Unlock()
	fake.SignatureStub = nil
	if fake.signatureReturnsOnCall == nil {
		fake.signatureReturnsOnCall = make(map[int]struct {
			result1 sbom.GetSignature
		})
	}
	fake.signatureReturnsOnCall[i] = struct {
		result1 sbom.GetSignature
	}{result1}
}

func (fake *FakeDocument) Spec() sbom.Spec {
	fake.specMutex.Lock()
	ret, specificReturn := fake.specReturnsOnCall[len(fake.specArgsForCall)]
	fake.specArgsForCall = append(fake.specArgsForCall, struct {
	}{})
	stub := fake.SpecStub
	fakeReturns := fake.specReturns
	fake.recordInvocation("Spec", []interface{}{})
	fake.specMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDocument) SpecCallCount() int {
	fake.specMutex.RLock()
	defer fake.specMutex.RUnlock()
	return len(fake.specArgsForCall)
}

func (fake *FakeDocument) SpecCalls(stub func() sbom.Spec) {
	fake.specMutex.Lock()
	defer fake.specMutex.Unlock()
	fake.SpecStub = stub
}

func (fake *FakeDocument) SpecReturns(result1 sbom.Spec) {
	fake.specMutex.Lock()
	defer fake.specMutex.Unlock()
	fake.SpecStub = nil
	fake.specReturns = struct {
		result1 sbom.Spec
	}{result1}
}

func (fake *FakeDocument) SpecReturnsOnCall(i int, result1 sbom.Spec) {
	fake.specMutex.Lock()
	defer fake.specMutex.Unlock()
	fake.SpecStub = nil
	if fake.specReturnsOnCall == nil {
		fake.specReturnsOnCall = make(map[int]struct {
			result1 sbom.Spec
		})
	}
	fake.specReturnsOnCall[i] = struct {
		result1 sbom.Spec
	}{result1}
}

func (fake *FakeDocument) Supplier() sbom.GetSupplier {
	fake.supplierMutex.Lock()
	ret, specificReturn := fake.supplierReturnsOnCall[len(fake.supplierArgsForCall)]
	fake.supplierArgsForCall = append(fake.supplierArgsForCall, struct {
	}{})
	stub := fake.SupplierStub
	fakeReturns := fake.supplierReturns
	fake.recordInvocation("Supplier", []interface{}{})
	fake.supplierMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDocument) SupplierCallCount() int {
	fake.supplierMutex.RLock()
	defer fake.supplierMutex.RUnlock()
	return len(fake.supplierArgsForCall)
}

func (fake *FakeDocument) SupplierCalls(stub func() sbom.GetSupplier) {
	fake.supplierMutex.Lock()
	defer fake.supplierMutex.Unlock()
	fake.SupplierStub = stub
}

func (fake *FakeDocument) SupplierReturns(result1 sbom.GetSupplier) {
	fake.supplierMutex.Lock()
	defer fake.supplierMutex.Unlock()
	fake.SupplierStub = nil
	fake.supplierReturns = struct {
		result1 sbom.GetSupplier
	}{result1}
}

func (fake *FakeDocument) SupplierReturnsOnCall(i int, result1 sbom.GetSupplier) {
	fake.supplierMutex.Lock()
	defer fake.supplierMutex.Unlock()
	fake.SupplierStub = nil
	if fake.supplierReturnsOnCall == nil {
		fake.supplierReturnsOnCall = make(map[int]struct {
			result1 sbom.GetSupplier
		})
	}
	fake.supplierReturnsOnCall[i] = struct {
		result1 sbom.GetSupplier
	}{result1}
}

func (fake *FakeDocument) Tools() []sbom.GetTool {
	fake.toolsMutex.Lock()
	ret, specificReturn := fake.toolsReturnsOnCall[len(fake.toolsArgsForCall)]
	fake.toolsArgsForCall = append(fake.toolsArgsForCall, struct {
	}{})
	stub := fake.ToolsStub
	fakeReturns := fake.toolsReturns
	fake.recordInvocation("Tools", []interface{}{})
	fake.toolsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDocument) ToolsCallCount() int {
	fake.toolsMutex.RLock()
	defer fake.toolsMutex.RUnlock()
	return len(fake.toolsArgsForCall)
}

func (fake *FakeDocument) ToolsCalls(stub func() []sbom.GetTool) {
	fake.toolsMutex.Lock()
	defer fake.toolsMutex.Unlock()
	fake.ToolsStub = stub
}

func (fake *FakeDocument) ToolsReturns(result1 []sbom.GetTool) {
	fake.toolsMutex.Lock()
	defer fake.toolsMutex.Unlock()
	fake.ToolsStub = nil
	fake.toolsReturns = struct {
		result1 []sbom.GetTool
	}{result1}
}

func (fake *FakeDocument) ToolsReturnsOnCall(i int, result1 []sbom.GetTool) {
	fake.toolsMutex.Lock()
	defer fake.toolsMutex.Unlock()
	fake.ToolsStub = nil
	if fake.toolsReturnsOnCall == nil {
		fake.toolsReturnsOnCall = make(map[int]struct {
			result1 []sbom.GetTool
		})
	}
	fake.toolsReturnsOnCall[i] = struct {
		result1 []sbom.GetTool
	}{result1}
}

func (fake *FakeDocument) Vulnerabilities() []sbom.GetVulnerabilities {
	fake.vulnerabilitiesMutex.Lock()
	ret, specificReturn := fake.vulnerabilitiesReturnsOnCall[len(fake.vulnerabilitiesArgsForCall)]
	fake.vulnerabilitiesArgsForCall = append(fake.vulnerabilitiesArgsForCall, struct {
	}{})
	stub := fake.VulnerabilitiesStub
	fakeReturns := fake.vulnerabilitiesReturns
	fake.recordInvocation("Vulnerabilities", []interface{}{})
	fake.vulnerabilitiesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDocument) VulnerabilitiesCallCount() int {
	fake.vulnerabilitiesMutex.RLock()
	defer fake.vulnerabilitiesMutex.RUnlock()
	return len(fake.vulnerabilitiesArgsForCall)
}

func (fake *FakeDocument) VulnerabilitiesCalls(stub func() []sbom.GetVulnerabilities) {
	fake.vulnerabilitiesMutex.Lock()
	defer fake.vulnerabilitiesMutex.Unlock()
	fake.VulnerabilitiesStub = stub
}

func (fake *FakeDocument) VulnerabilitiesReturns(result1 []sbom.GetVulnerabilities) {
	fake.vulnerabilitiesMutex.Lock()
	defer fake.vulnerabilitiesMutex.Unlock()
	fake.VulnerabilitiesStub = nil
	fake.vulnerabilitiesReturns = struct {
		result1 []sbom.GetVulnerabilities
	}{result1}
}

func (fake *FakeDocument) VulnerabilitiesReturnsOnCall(i int, result1 []sbom.GetVulnerabilities) {
	fake.vulnerabilitiesMutex.Lock()
	defer fake.vulnerabilitiesMutex.Unlock()
	fake.VulnerabilitiesStub = nil
	if fake.vulnerabilitiesReturnsOnCall == nil {
		fake.vulnerabilitiesReturnsOnCall = make(map[int]struct {
			result1 []sbom.GetVulnerabilities
		})
	}
	fake.vulnerabilitiesReturnsOnCall[i] = struct {
		result1 []sbom.GetVulnerabilities
	}{result1}
}

func (fake *FakeDocument) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDocument) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sbom.Document = new(FakeDocument)
